### ISSUE TITLE
flutter_built_redux should not be tagged server

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pana#100]
https://pub.dartlang.org/packages/flutter_built_redux

Depends on package: flutter directly, yet is classified as "server" :)

I've seen other flutter packages tagged this way.

**Comment by isoos** [comment]
Yeah, at the moment we classify packages as flutter-only if there is a top-level 'flutter:' key in the pubspec.yaml. I gather if you flutter as direct dependency, it is the same thing. Fix is on the way...
