### ISSUE TITLE
Teach pana how to distinguish tools from packages?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/pana#1008]
pub.dev lists [reflectable](https://pub.dev/packages/reflectable/score) 3.0.0 as _not_ supporting sound null safety. It seems likely that this is based on the fact that at least one of the libraries in this package contains `@dart = 2.9`, or it occurs because at least one library imports a library that isn't considered null safe.

However, this package consists of some libraries that implement a code generator, and other libraries that are imported by client packages using reflectable. The libraries that are imported into client programs are fully migrated to null safety, it is only the code generator that depends on some packages/libraries that aren't yet fully migrated (hence, a couple of libraries in the code generator contain `@dart = 2.9`).

There are 69 tests running with sound null safety, so it's well established that client programs can be fully null safe.

Is there a way to make this distinction, indicating that a package with both client-imported libraries and "tool" libraries can work as a fully null safe package, even though it contains one or more tools that haven't yet finished the migration?

**Comment by sigurdm** [comment]
Closing this in favor of: https://github.com/dart-lang/pana/issues/1008
