### ISSUE TITLE
ignore naming lints in dart:ffi bindings

### ISSUE THREAD

**Issue by leisim** [dart-lang/pana#1011]
My [package](https://pub.dev/packages/isar/versions/2.0.0/score) got a lower rating because there is an ffi bindings file with non-lowerCamelCase native names.

I excluded it in the `analysis_options.yaml` but there is still a penalty.

(Please ignore the `Unused import: 'package:ffi/ffi.dart'` in the latest version that was my mistake. Previous versions don't have it)

**Comment by isoos** [comment]
@leisim: thanks for reporting this, I think we should ignore the lints that are ffi-binding related. However, until it happens, you may override the lint for the line or for the file. We use a custom `analysis_options.yaml`, so overriding there won't work for now.

**Comment by sigurdm** [comment]
By providing a preamble to ffigen you can ignore these for the generated code: https://github.com/google/webcrypto.dart/blob/master/lib/src/third_party/boringssl/ffigen.yaml

Perhaps this should be done by default.

**Comment by sigurdm** [comment]
Closing this in favor of the ffi-gen issue.
