### ISSUE TITLE
`--exit-code-threshold` does not cause a non-zero exit code

### ISSUE THREAD

**Issue by Jordan-Nelson** [dart-lang/pana#1024]
### Issue

Running `pana --exit-code-threshold 0 .` does not cause a non-zero exit even when the package is missing points.

### Reproduction steps

1. Clone a repository that is missing pub points. I am using https://pub.dev/packages/amplify_authenticator, which is scoring 110/120.
2. Run `pana --exit-code-threshold 0 .`
3. Observe that the output indicates that the package is missing points, but the process completes normally. 

#### Output
<details>

INFO       Running `/Users/nejrd/development/flutter/bin/cache/dart-sdk/bin/dart --version`...
INFO       Running `flutter --no-version-check --version --machine`...
WARNING    pana might update or modify files in `.`.
           Analysis will begin in 15 seconds, hit CTRL+C to abort it.
           To remove this message, use `--no-warning`.
INFO       Running `git rev-parse --show-toplevel`...
INFO       Running `flutter --no-version-check packages pub upgrade --verbose`...
SEVERE     Problem with `dart pub upgrade`
           Bad state: For amplify_analytics_plugin_interface, the parsed version null did not match the locked version 0.4.0.
           #0      _validateLockedVersions.<anonymous closure> (package:pana/src/pkg_resolution.dart:221:11)
           #1      SplayTreeMap.forEach (dart:collection/splay_tree.dart:604:8)
           #2      _validateLockedVersions (package:pana/src/pkg_resolution.dart:217:12)
           #3      createPkgResolution (package:pana/src/pkg_resolution.dart:203:5)
           #4      PackageContext.resolveDependencies (package:pana/src/package_context.dart:67:26)
           <asynchronous suspension>
           #5      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:138:27)
           <asynchronous suspension>
           #6      PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:91:14)
           <asynchronous suspension>
           #7      withTempDir (package:pana/src/utils.dart:233:12)
           <asynchronous suspension>
           #8      main (file:///Users/nejrd/.pub-cache/hosted/pub.dartlang.org/pana-0.21.7/bin/pana.dart:172:19)
           <asynchronous suspension>
INFO       Analyzing package...
INFO       Running `/Users/nejrd/development/flutter/bin/cache/dart-sdk/bin/dart analyze --format machine lib`...
INFO       Running `flutter --no-version-check format --output=none --set-exit-if-changed /private/var/folders/3n/3plhqvn96jq6thcpd50d2pgh0000gr/T/pana_0Ya6tg/packages/amplify_authenticator/lib`...
INFO       Running `/Users/nejrd/development/flutter/bin/cache/dart-sdk/bin/dart pub get .`...
INFO       Running `/Users/nejrd/development/flutter/bin/cache/dart-sdk/bin/dart pub outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...

### [*] 10/10 points: Package has an example

* Found example at: `example/lib/main.dart`

### [*] 20/20 points: Supports 2 of 6 possible platforms (**iOS**, **Android**, Web, Windows, MacOS, Linux)

* ✓ Android
* ✓ iOS

These platforms are not supported:

<details>
<summary>
Package does not support platform `Windows`.
</summary>

Because:
* `package:amplify_authenticator/amplify_authenticator.dart` that imports:
* `package:amplify_authenticator/src/widgets/form_field.dart` that imports:
* `package:amplify_authenticator/src/widgets/form.dart` that imports:
* `package:amplify_flutter/amplify_flutter.dart` that declares support for platforms: `Android`, `iOS`.
</details>
<details>
<summary>
Package does not support platform `Linux`.
</summary>

Because:
* `package:amplify_authenticator/amplify_authenticator.dart` that imports:
* `package:amplify_authenticator/src/widgets/form_field.dart` that imports:
* `package:amplify_authenticator/src/widgets/form.dart` that imports:
* `package:amplify_flutter/amplify_flutter.dart` that declares support for platforms: `Android`, `iOS`.
</details>
<details>
<summary>
Package does not support platform `macOS`.
</summary>

Because:
* `package:amplify_authenticator/amplify_authenticator.dart` that imports:
* `package:amplify_authenticator/src/widgets/form_field.dart` that imports:
* `package:amplify_authenticator/src/widgets/form.dart` that imports:
* `package:amplify_flutter/amplify_flutter.dart` that declares support for platforms: `Android`, `iOS`.
</details>
<details>
<summary>
Package does not support platform `Web`.
</summary>

Because:
* `package:amplify_authenticator/amplify_authenticator.dart` that imports:
* `package:amplify_authenticator/src/widgets/form_field.dart` that imports:
* `package:amplify_authenticator/src/widgets/form.dart` that imports:
* `package:amplify_flutter/amplify_flutter.dart` that declares support for platforms: `Android`, `iOS`.
</details>

### [~] 20/30 points: code has no errors, warnings, lints, or formatting issues

<details>
<summary>
INFO: Don't import implementation files from another package.
</summary>

`lib/src/services/amplify_auth_service.dart:21:8`

```
   ╷
21 │ import 'package:collection/src/iterable_extensions.dart';
   │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

To reproduce make sure you are using the [lints_core](https://pub.dev/packages/lints) and run `flutter analyze lib/src/services/amplify_auth_service.dart`
</details>

### [*] 10/10 points: All of the package dependencies are supported in the latest version

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`amplify_auth_cognito`]|`>=0.3.0 <0.5.0`|0.4.0|0.4.0|
|[`amplify_auth_plugin_interface`]|`>=0.3.0 <0.5.0`|0.4.0|0.4.0|
|[`amplify_core`]|`>=0.3.0 <0.5.0`|0.4.0|0.4.0|
|[`amplify_flutter`]|`>=0.3.0 <0.5.0`|0.4.0|0.4.0|
|[`collection`]|`^1.15.0`|1.15.0|1.15.0|
|[`flutter`]|`flutter`|0.0.0|0.0.0|
|[`flutter_localizations`]|`flutter`|0.0.0|0.0.0|
|[`intl`]|`^0.17.0`|0.17.0|0.17.0|

<details><summary>Transitive dependencies</summary>

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`amplify_analytics_plugin_interface`]|-|0.4.0|0.4.0|
|[`amplify_api_plugin_interface`]|-|0.4.0|0.4.0|
|[`amplify_datastore_plugin_interface`]|-|0.4.0|0.4.0|
|[`amplify_storage_plugin_interface`]|-|0.4.0|0.4.0|
|[`characters`]|-|1.2.0|1.2.0|
|[`clock`]|-|1.1.0|1.1.0|
|[`crypto`]|-|3.0.1|3.0.1|
|[`date_time_format`]|-|2.0.1|2.0.1|
|[`json_annotation`]|-|4.4.0|4.4.0|
|[`material_color_utilities`]|-|0.1.3|0.1.4|
|[`meta`]|-|1.7.0|1.7.0|
|[`plugin_platform_interface`]|-|2.1.2|2.1.2|
|[`sky_engine`]|-|0.0.99|0.0.99|
|[`typed_data`]|-|1.3.0|1.3.0|
|[`uuid`]|-|3.0.6|3.0.6|
|[`vector_math`]|-|2.1.1|2.1.2|
</details>

To reproduce run `dart pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides`.

[`amplify_auth_cognito`]: https://pub.dev/packages/amplify_auth_cognito
[`amplify_auth_plugin_interface`]: https://pub.dev/packages/amplify_auth_plugin_interface
[`amplify_core`]: https://pub.dev/packages/amplify_core
[`amplify_flutter`]: https://pub.dev/packages/amplify_flutter
[`collection`]: https://pub.dev/packages/collection
[`flutter`]: https://pub.dev/packages/flutter
[`flutter_localizations`]: https://pub.dev/packages/flutter_localizations
[`intl`]: https://pub.dev/packages/intl
[`amplify_analytics_plugin_interface`]: https://pub.dev/packages/amplify_analytics_plugin_interface
[`amplify_api_plugin_interface`]: https://pub.dev/packages/amplify_api_plugin_interface
[`amplify_datastore_plugin_interface`]: https://pub.dev/packages/amplify_datastore_plugin_interface
[`amplify_storage_plugin_interface`]: https://pub.dev/packages/amplify_storage_plugin_interface
[`characters`]: https://pub.dev/packages/characters
[`clock`]: https://pub.dev/packages/clock
[`crypto`]: https://pub.dev/packages/crypto
[`date_time_format`]: https://pub.dev/packages/date_time_format
[`json_annotation`]: https://pub.dev/packages/json_annotation
[`material_color_utilities`]: https://pub.dev/packages/material_color_utilities
[`meta`]: https://pub.dev/packages/meta
[`plugin_platform_interface`]: https://pub.dev/packages/plugin_platform_interface
[`sky_engine`]: https://pub.dev/packages/sky_engine
[`typed_data`]: https://pub.dev/packages/typed_data
[`uuid`]: https://pub.dev/packages/uuid
[`vector_math`]: https://pub.dev/packages/vector_math

### [*] 20/20 points: Package and dependencies are fully migrated to null safety!

Points: 110/120.

</details>

Am I misunderstanding the intention behind `--exit-code-threshold`?

**Comment by Jordan-Nelson** [comment]
Never mind. There is a non 0 exit code. I had assumed the exit code was 0 since the log output is identical to the output with `--exit-code-threshold` omitted. It might make sense differentiate the log output for a non-zero exit (example: `--set-exit-if-changed` for `flutter format`).

I am going to close this issue though since it is working as expected.

**Comment by mrverdant13** [comment]
Maybe related #1025
