### ISSUE TITLE
Should we deduct points for lints that are manually excluded?

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pana#1029]
A package like [win32](https://pub.dev/packages/win32/score) has a custom set of lints defined in [`analysis_options.yaml`](https://github.com/timsneath/win32/blob/main/analysis_options.yaml). In most cases, this list is _stricter_ than the recommended lints, but sometimes it makes sense to disable a general-purpose lint for the specific needs of the package. 

For example, constants in Windows are [`SCREAMING_CAPS`](https://github.com/timsneath/win32/blob/main/lib/src/constants.dart), so it makes sense that they are similarly defined in Dart. Attempting to define them differently would result in a cascade of name clashes and cause endless confusion.

Similarly, there is a file `IUnknown.dart` that defines the `IUnknown` class, which is a standard COM object, known universally by that name in every language. It would be eccentric to name that something like `Iunknown` to match a Dart lint.  

I'm currently faced with the unpalatable choice of either naming objects in ways that will surprise package users, or accepting a low score because I'm doing the 'right' thing: 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2319867/157111640-a1ce2ed5-0e2f-491d-820a-a744699943e4.png">

I recognize that it's difficult to come up with generally applicable rules here, but should we not measure packages against the lints that they define, rather than a generic list that may include false positives?

**Comment by natebosch** [comment]
I don't think it's sensible to allow package authors to change their scores in pub by disabling diagnostics.

It's definitely a challenge making the style choices to bridge the gap between two languages/ecosystems. FWIW I think it's sensible that the choice to prioritize the foreign language is reflected in the pub score - that doesn't necessarily meant it's the wrong choice, but it's an accurate reflection of the tradeoff.

> Similarly, there is a file `IUnknown.dart` that defines the `IUnknown` class, which is a standard COM object, known universally by that name in every language.

The file could be `i_unknown.dart` to satisfy the files names lint and define a `class IUnknown`. Note that imports aren't necessarily case sensitive everywhere, so I'd avoid trying to enforce imports with capitals.

> It would be eccentric to name that something like `Iunknown` to match a Dart lint.

I'm not familiar with any lint that would complain about `class IUnknown`, and if we have one turned on in pub we should look at turning it off...

**Comment by timsneath** [comment]
You're right that a class `IUnknown` doesn't throw an error. I was thinking of [`camel_case_types`](https://dart-lang.github.io/linter/lints/camel_case_types.html), but that doesn't complain. 

Speaking here purely as an individual community member, I guess I don't see it as "disabling diagnostics"; it simply seems problematic to me that a package that does the right thing for its context is penalized for doing so. 

While a package author could manually disable all lints to artificially improve their score, it would seem pointless to do so - since it would be as easy to fix the lints. Conversely, a well-meaning package author understands their code best, and presumably if they are disabling a specific lint, it's likely because they have a good reason to do so.

I'm told that using `// ignore_for_file:<lint>` disables a lint for a file in a way that won't be penalized, which I can obviously do for each file. It just seems a little unnecessary.

**Comment by sigurdm** [comment]
> I'm told that using // ignore_for_file:<lint> disables a lint for a file in a way that won't be penalized, which I can obviously do for each file. It just seems a little unnecessary.

I think that is the solution we'll recommend for now.

Please reopen if that seems too much of a burden in some cases.
