### ISSUE TITLE
Grant 10 points for successful license detection

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#1037]
I propose that we grant 10 points to packages with a `LICENSE` file from which we can detect a license.

We are currently to detect the license of most packages, see:
https://github.com/dart-lang/pub-dev/issues/4373#issuecomment-1042778403

Investigation of which license we fail to detect is filed as https://github.com/dart-lang/pana/issues/1015

Packages that don't use one of the licenses from https://github.com/dart-lang/pana/tree/master/lib/src/third_party/spdx/licenses won't get these 10 points. That is unfortunate for packages with a commercial license. But we could say that if the `LICENSE` file starts with the string:
> `**THIS PACKAGE REQUIRES A COMMERCIAL LICENSE**\n` (followed by whatever license the package wants to use)

Then we detect the license as `license:commercial` or `license:proprietary` and grant the 10 points. So we simply have a string that indicates the package is commercial and we shouldn't do license detection for it.

When license detection fails, we can link to a page on dart.dev that explains:
 * How license detection on `LICENSE` works, and how to run pana's license detection locally.
 * How opt-out of license detection by marking a package a commercial (using the magic string).

![9TSBF86jmQEBGSa (1)](https://user-images.githubusercontent.com/149732/158828062-66c57e43-e03b-4832-9d28-36eaee384ebc.png)

-----------------------

**Questions:**
 * What string should we use in `LICENSE` to indicate a proprietary / commercial package?
    * Option: `**THIS PACKAGE IS COMMERCIALLY LICENSED**\n`
    * Option: `**THIS PACKAGE REQUIRES A COMMERCIAL LICENSE**\n`
 * Should we use the term `license:commercial` in the UI?
    * Option: `license:proprietary`
    * Option: `license:commercial`

**Comment by jonasfj** [comment]
A solid counter argument is that there could be commercial SPDX licenses. There probably isn't any, but could there be that in the future?

**Comment by jonasfj** [comment]
@mit-mit any thoughts?

**Comment by timsneath** [comment]
I like this idea; flagging @mit-mit for review again. 

One slightly controversial idea would be to only give points (or give extra points) to known OSS licenses, as an incentive to others to contribute open source code that others can in turn adapt or fork. While a commercial publisher may choose to publish under a proprietary or non-standard license, our culture rewards those who share back. (As an added bonus, it might also simplify the logic?)

**Comment by mit-mit** [comment]
Granting 10 additional points to successfully detected, known "good" OSS licenses SGTM

**Comment by sigurdm** [comment]
I'm not really opposed to this - but I think we will get some backlash for rewarding fewer points to commercial packages. Maybe a badge would be better?

**Comment by timsneath** [comment]
I'm willing to accept that, honestly. We want to encourage commercial packages also, but instead of 10 points they get $$$! We reward sharing (with extra points), but don't penalize not sharing (since we don't _subtract_ points).

**Comment by sigurdm** [comment]
One issue with trading points for payment is that the search results are ordered by (together with other factors) the package score.

Is it clear that we always want to show a commercial package below an open source package (other things being equal)?

If that is what we want we should go ahead!

**Comment by timsneath** [comment]
I think the "other things being equal" part is what carries the weight here. Our search relevancy isn't nearly good enough today that this is the dominating force, unfortunately. 

The one that came to mind was Syncfusion's [great commercial chart package](https://www.syncfusion.com/flutter-widgets/flutter-charts). Would it get buried if it "only" had 130 points? 

And so I did a search for chart: https://pub.dev/packages?q=chart. Frankly, the results are pretty bad; the top result is not compatible with Dart 2, and then we list Material and Cupertino despite neither having any charting widgets; another SyncFusion package is on the first page, at least, but it's below other packages like d_chart that have fewer likes, pub points and popularity. The main [Syncfusion charting package](https://pub.dev/packages/syncfusion_flutter_charts) is on page 6 despite having 1950 likes and 99% popularity -- more than all but one of the packages on the first page. 

That is, I don't think this is the gating factor.

**Comment by isoos** [comment]
> the top result is not compatible with Dart 2, and then we list Material and Cupertino despite neither having any charting widgets

The top result is direct name match, which we always list, regardless of the Dart 2 compatibility. Both Material and Cupertino library has [chart_bar icon](https://api.flutter.dev/flutter/cupertino/CupertinoIcons/chart_bar-constant.html). Neither is a great match in the context, we should down-rank their weights, but API listing is tricky, as in other contexts it should be shown.

> another SyncFusion package is on the first page, at least, but it's below other packages like d_chart that have fewer likes, pub points and popularity.

That looks like a strange result, we should investigate why it happens. We should probably reduce the weight of the partial name matches and increase the score/popularity weight even more. I suspect the same thing happens with the other syncfusion library.

**Comment by sigurdm** [comment]
> The top result is direct name match, which we always list, regardless of the Dart 2 compatibility. 

We should really indicate when a search result is a direct name match.
