### ISSUE TITLE
ISC License

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/pana#1071]
Please add support for ISC licenses.
Currently they are shown as unknown, for example here: https://pub.dev/packages/weak_cache/license

**Comment by isoos** [comment]
We are using SPDX's license data from the https://github.com/spdx/license-list-data repository, which does have the ISC license in it: https://github.com/dart-lang/pana/blob/master/lib/src/third_party/spdx/licenses/ISC.txt

However, it seems that the difference between your license and the SPDX text is too large, and we wouldn't classify it as such. I am no authority on what the official SPDX reference should look like, but maybe the `ISC` should be replaced with `THE AUTHOR`, and the copyright lines seem to be excessive. If you are interested, I think changes to SPDX may be submitted to https://github.com/spdx/license-list-XML

On our part, we should probably also revisit the preparation of both the reference texts and the license in question, it may help the recognition, maybe we can do reasonable preprocessing to make it a match within the acceptance threshold.

**Comment by Zekfad** [comment]
Thanks for your reply!

Main difference in text is newlines i added to make it readable without word wrapping.

Also GitHub does recognize my license as ISC: https://github.com/Zekfad/weak_cache/blob/master/LICENSE
