### ISSUE TITLE
dart:mirrors shouldn't disqualify platform:linux

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#1092]
From `package:pigeon`:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/4778111/179915130-2ec77f99-f7e1-4943-9a32-42449900e2bb.png">

**Comment by mraleph** [comment]
It would be nice to get this fixed. Currently a package like https://pub.dev/packages/steward has no platform compatibility for no good reason.

**Comment by sigurdm** [comment]
This would be a good candidate for: https://github.com/dart-lang/pub-dev/issues/6400

**Comment by sigurdm** [comment]
We believe this is fixed!
