### ISSUE TITLE
Unable to access git repository: Could not find HEAD branch on non English computer

### ISSUE THREAD

**Issue by dumabg** [dart-lang/pana#1095]
My computer is in Spanish. Git messages appears in Spanish.

Pana doesn't find the HEAD branch because assumes the messages in English:

`Unable to access git repository: Could not find HEAD branch.
           Could not find HEAD branch.
           
     #0      GitLocalRepository.detectDefaultBranch (package:pana/src/repository/git_local_repository.dart:119:5)
           <asynchronous suspension>
           #1      checkRepository (package:pana/src/repository/check_repository.dart:73:16)
           <asynchronous suspension>
           #2      checkPubspecUrls (package:pana/src/references/pubspec_urls.dart:56:30)
           <asynchronous suspension>
           #3      followsTemplate.checkPubspec (package:pana/src/report/template.dart:185:25)
           <asynchronous suspension>
           #4      followsTemplate (package:pana/src/report/template.dart:253:26)
           <asynchronous suspension>
           #5      createReport (package:pana/src/report/create_report.dart:42:5)
           <asynchronous suspension>
           #6      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:251:15)
           <asynchronous suspension>
           #7      PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:98:14)
           <asynchronous suspension>
           #8      withTempDir (package:pana/src/utils.dart:235:12)
           <asynchronous suspension>
           #9      main (file:///home/dumabg/.pub-cache/hosted/pub.dartlang.org/pana-0.21.14/bin/pana.dart:174:19)
           <asynchronous suspension> `

**Comment by isoos** [comment]
@dumabg: could you please run the following command and copy-paste the first 5-8 lines output from it?
```
git remote show origin
```

My current output for pana:

```
* remote origin
  Fetch URL: https://github.com/isoos/pana.git
  Push  URL: https://github.com/isoos/pana.git
  HEAD branch: master
  Remote branches:
```

I'm looking for the pattern that is around the `HEAD branch` part...

**Comment by dumabg** [comment]
```
remoto origin
             URL  para obtener: https://github.com/dumabg/test_screen
             URL para publicar: https://github.com/dumabg/test_screen
             Rama HEAD: main
             Rama remota
```
