### ISSUE TITLE
consider environment -> flutter in pubspec analysis?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#110]
https://www.dartlang.org/tools/pub/pubspec#flutter-sdk-constraints

To discuss.

**Comment by isoos** [comment]
Is that environment entry a substitute for the `flutter` entry in `dependencies`?

**Comment by kevmoo** [comment]
> Is that environment entry a substitute for the flutter entry in dependencies?

I don't know 🤷‍♂️
