### ISSUE TITLE
pkg:flutter_bloc outdated dependencies

### ISSUE THREAD

**Issue by felangel** [dart-lang/pana#1112]
URL: https://pub.dev/packages/flutter_bloc/score

<Describe your issue or suggestion here>
10 points were deducted for outdated dependencies even though that is not the case. Pana penalizes the package due to dependency_overrides in the example which use a path. This must be a new check since this wasn’t ever a problem as far as I recall.

**Comment by isoos** [comment]
This is fixed via #1116.
