### ISSUE TITLE
Path dependency on other package in repository in `example` project fails pana check

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/pana#1118]
Here's an example repo structure:
```
my_repository
├── project_1
│   └── example
│       └── pubspec.yaml
└── project_2
```

Contents of `my_repository/project_1/example/pubspec.yaml`:
```yaml
dependencies:
  project_2:
    path: ../../project_2
```

This used to not cause any issues with pana, but now my packages that do this are getting the following error on pub.dev:

Support up-to-date dependencies 10/20
0/10 points: All of the package dependencies are supported in the latest version
Could not run flutter pub outdated: flutter pub get failed:
```
OUT:
Running "flutter pub get" in ....                                  872ms
Running "flutter pub get" in example...
ERR:
Because watch_connectivity_example depends on watch_connectivity_platform_interface from path which doesn't exist (could not find package watch_connectivity_platform_interface at "../../watch_con[...]
```

[Here's a link to the package with that error](https://pub.dev/packages/watch_connectivity/score)

**Comment by isoos** [comment]
This has been fixed with #1116, and we should release a new version of pana and pub.dev with it soon...
