### ISSUE TITLE
Example source-code is not detected if present in bin folder

### ISSUE THREAD

**Issue by freitzzz** [dart-lang/pana#1120]
Hi all

It seems `bin/<project_name>` is the new convention for providing entry points to Dart programs. If another one is provided (e.g., `lib/<project_name>`, attempting to execute `dart run` will output the following:

```
Could not find bin/<project_name>.dart in package <project_name>.
```

However, PANA (I assume) is not detecting example source-code in the `bin` directory, as stated in the official doc: https://dart.dev/tools/pub/package-layout#examples

Given this constraint, shouldn't PANA be updated to support the `bin` directory as the example source-of-truth?

Package in pub where this occurred: https://pub.dev/packages/networking

**Comment by freitzzz** [comment]
Understood.

The problem is: as package developers, apart from showing example code on pub.dev, we also want people to download the package and be able to test right away, which is done via `dart run`.

**Comment by freitzzz** [comment]
Do you have any recommendations on how to circumvent the need to provide the example code in `bin` and also on `lib` or README?

**Comment by sigurdm** [comment]
`dart run example/bin/foo.dart` should work.

**Comment by freitzzz** [comment]
decided to put the example code in `lib` and then reference it on `bin`, that way `dart run` works as expected

closing as this doesn't seem to be an issue in my pov
