### ISSUE TITLE
Explain that "Unknown Platforms" is because static analysis of package failed.

### ISSUE THREAD

**Issue by ashitaprasad** [dart-lang/pana#1134]
Various packages like [awesome_select](https://pub.dev/packages/awesome_select/score), [progress_indicator_button](https://pub.dev/packages/progress_indicator_button/score) and others have been tagged as "Unknown Platforms" although the Platform support section shows no error (Supports 6 of 6 possible platforms).

A thing to note is that both these packages failed to pass the static analysis. Is this the cause of this issue?

**Comment by isoos** [comment]
The linked packages has serious failures in their static analysis, and in such cases we don't assign platform tags to the package.

**Comment by isoos** [comment]
We've since updated the label that indicates static analysis issue.
