### ISSUE TITLE
pubspec.yaml with homepage: to github.com should show "Repository (GitHub)" instead of "Homepage" link

### ISSUE THREAD

**Issue by eseidel** [dart-lang/pana#1159]
e.g. https://pub.dev/packages/process_run has homepage: github.com..., so it shows:

```
[Homepage](https://github.com/tekartik/process_run.dart)

Process run helpers for Linux/Win/Mac and which like feature for finding executables.

Metadata
```

Where as:
https://pub.dev/packages/analyzer
(correctly) uses the newer "repository: github.com..." and thus shows:

```
Metadata
This package provides a library that performs static analysis of Dart code.

[Repository (GitHub)](https://github.com/dart-lang/sdk/tree/main/pkg/analyzer)
[View/report issues](https://github.com/dart-lang/sdk/issues)
```

**Comment by isoos** [comment]
This non-verification patch has been deployed a few weeks ago, and the repository verification is planned to roll out in early January. Closing this as we don't have much else to do with the issue.
