### ISSUE TITLE
What is `dart:html_common`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#1219]
See analysis issues in https://pub.dev/packages/sembast_web/score

**Comment by sigurdm** [comment]
Seems it exists:
https://github.com/dart-lang/sdk/blob/main/sdk/lib/libraries.yaml#L213
But isn't documented:
https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart#L91
