### ISSUE TITLE
[Question] Identify undocumented API elements.

### ISSUE THREAD

**Issue by HeySreelal** [dart-lang/pana#1223]
Hey! I've uploaded a package to pub.dev. I saw the following line in the scoring section:

`2869 out of 2899 API elements (99.0 %) have documentation comments`

But is there any way I can find those undocumented API elements with Pana?

**Comment by isoos** [comment]
@HeySreelal: maybe this lint could be enabled in your local analysis-options.yaml?
https://dart-lang.github.io/linter/lints/public_member_api_docs.html
https://dart.dev/guides/language/analysis-options

**Comment by HeySreelal** [comment]
Hey, thank you so much for the suggestion @isoos. I've tried enabling the mentioned lint rule. I could find 5 more API elements that weren't documented with dartdoc comments.

But clearly, there are a few more API elements left to be documented. 

Thanks again, is there anything else I can do to find these uncommented API elements, or could the warning message be false info? 

Regards :)

**Comment by isoos** [comment]
> But clearly, there are a few more API elements left to be documented.

Maybe the library definitions? But to be honest, 99% is really good coverage, you may not need to stress out on it...
