### ISSUE TITLE
Losing points due to too large changelog

### ISSUE THREAD

**Issue by spydon** [dart-lang/pana#1264]
![image](https://github.com/dart-lang/pub-dev/assets/744771/441c746e-889f-414c-ab73-8f43973d2f85)

In Flame we have an exceptionally good [changelog](https://github.com/flame-engine/flame/blob/main/packages/flame/CHANGELOG.md), I think it sends the wrong signals from Pub to get minus points for this.
(Although we are very happy that we can now publish without modifications after the size limit was [bumped to 256KB](https://github.com/dart-lang/pub-dev/pull/7065)! 🥳)

If there is a technical issue by pub not being able to handle the file size, I think there should be a proper solution for this and something that should be solved on Pub's side, not on the package author's side.

Related: dart-lang/pub-dev#6012

Any new users searching for how to keep a good changelog will get results like these in the top:
https://keepachangelog.com/
https://docs.gitlab.com/ee/development/changelog.html
https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md
https://www.freecodecamp.org/news/a-beginners-guide-to-git-what-is-a-changelog-and-how-to-generate-it/
None which recommend splitting up the changelog into multiple files. Keeping all changes in `CHANGELOG.md` has been the de facto open source standard for quite a while.

For search engines:
Provide a valid CHANGELOG.md
CHANGELOG.md too large

**Comment by sigurdm** [comment]
Maybe we can remove the check from pana entirely, since we have the size limit at upload time

**Comment by spydon** [comment]
Thanks for fixing this so incredibly quickly! 💙

**Comment by isoos** [comment]
@spydon: this is only merged now, it may take a while until this gets released on pub.dev

**Comment by spydon** [comment]
> @spydon: this is only merged now, it may take a while until this gets released on pub.dev

No worries, at least now we know that the fix will be there at some point.
