### ISSUE TITLE
Searching for non-flutter packages gives mainly flutter packages

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pana#1290]
With the query ["-sdk:flutter"](https://pub.dev/packages?q=-sdk%3Aflutter)
We get this:
![image](https://github.com/dart-lang/pub-dev/assets/8613953/799327a6-0778-43d2-8623-f0f79cf4d540)

Something seems to be broken somewhere

**Comment by isoos** [comment]
One conflict I've found so far that explains why the package doesn't get `sdk:flutter` tag:
```
Package is not compatible with the Flutter SDK. Because:
* `package:share_plus/share_plus.dart` that imports:
* `package:share_plus/src/share_plus_web.dart` that imports:
* `package:url_launcher_web/url_launcher_web.dart` that imports:
* `package:url_launcher_web/src/link.dart` that imports:
* `dart:ui_web`
```

**Comment by isoos** [comment]
#1259 added `ui_web`, but only for the platform detection library list, we need to add it to the SDK detection too.
