### ISSUE TITLE
0/10 for up to date dependencies due to "Found no Flutter in your PATH"

### ISSUE THREAD

**Issue by ethanblake4** [dart-lang/pana#1294]
https://pub.dev/packages/flutter_eval/score

Getting this strange error for my package's analysis score on Pub as of a few days ago:

> 0/10 points: Package supports latest stable Dart and Flutter SDKs
>   - Found no Flutter in your PATH. Could not determine the current Flutter version.

**Comment by sigurdm** [comment]
Not sure how this can happen. @isoos do you have any ideas?

**Comment by sigurdm** [comment]
Closing in favor of https://github.com/dart-lang/pub-dev/issues/7264 as this seems to be a pub-dev issue.
