### ISSUE TITLE
`Homepage URL doesn't exist` in pub.dev scan (it does exist)

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/pana#1307]
<img width="792" alt="Screenshot 2023-12-22 at 8 25 37 PM" src="https://github.com/dart-lang/pana/assets/7896519/914b8291-9b77-4f76-997c-b6a09a456014">

Several of my packages on pub.dev have this issue, but the git repos are reachable. It seems to be random which of my packages get this issue each scan. Maybe GitHub is rate-limiting the pub.dev scanner?

**Comment by isoos** [comment]
It could have been a rate limit or a temporary network issue, yeah. We should definitely restructure how we are doing this part of the analysis.

**Comment by Rexios80** [comment]
Closing since this hasn't happened in a while
