### ISSUE TITLE
Flutter detection fails when Flutter running for the first time

### ISSUE THREAD

**Issue by frknkrc44** [dart-lang/pana#1309]
Hi to everyone!

I prepared a GitHub action to check the PANA result, but it failed when Flutter runs for the first time because Flutter prints the welcome text.

I fixed it by adding another command: https://github.com/frknkrc44/easy_utils/actions/runs/7342286251/job/19991318753

Check the "Run analyzer" for more details: https://github.com/frknkrc44/easy_utils/actions/runs/7342195786/job/19991095416

```
{"logName":"pana","level":"INFO","message":"Running `flutter --no-version-check --version --machine`..."}
{"logName":"pana","level":"WARNING","message":"Unable to detect Flutter version.","error":"Exception: Unable to parse output as JSON:\n\n```\nOUT:\n{\n  \"frameworkVersion\": \"3.16.5\",\n  \"channel\": \"stable\",\n  \"repositoryUrl\": \"[https://github.com/flutter/flutter.git\](https://github.com/flutter/flutter.git/)",\n  \"frameworkRevision\": \"78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9\",\n  \"frameworkCommitDate\": \"2023-12-19 16:14:14 -0800\",\n  \"engineRevision\": \"3f3e560236539b7e2702f5ac790b2a4691b32d49\",\n  \"dartSdkVersion\": \"3.2.3\",\n  \"devToolsVersion\": \"2.28.4\",\n  \"flutterVersion\": \"3.16.5\",\n[45 more lines]\n```\n"}
```

**Comment by isoos** [comment]
I think we may expect this in the logs, but I'm not sure: does it affect the analysis too? At one point we were retrying after the version check.

**Comment by frknkrc44** [comment]
@isoos It just causes "Found no Flutter in your PATH. Could not determine the current Flutter version." error and reduces the project's total point (you can see it on summary).

**Comment by sigurdm** [comment]
This is related to https://github.com/flutter/flutter/issues/139737

We should probably implement christopherfujino's fix, and pass CI=true from pana

**Comment by isoos** [comment]
This was a pub.dev environment handling issue, which has been fixed. Closing this now.
