### ISSUE TITLE
Executing only parts of the analysation when you try to improve your package

### ISSUE THREAD

**Issue by rekire** [dart-lang/pana#1355]
I would like to improve the documentation since I missed some parts. However by default only the first 10 missing entries are shown and it checks all the other things too where I have already the full score. Therefore it would be great to execute only the parts I'm interested.

Something like `pana --only-dartdoc ./path` would be great.

**Comment by goderbauer** [comment]
There's also the `public_member_api_docs` lint [1] that flags all members missing API docs. That's what we use in the Flutter framework to make sure everything is documented.

cc @srawlins for dartdoc. 

[1] https://dart.dev/tools/linter-rules/public_member_api_docs

**Comment by sigurdm** [comment]
@rekire does the `public_member_api_docs` lint work well enough for you? That should give you a list of all missing docs when you run `dart analyze` (or right in the IDE).

**Comment by rekire** [comment]
I would need to check again, but I guess it is missing the `library;` statements.

**Comment by sigurdm** [comment]
We should probably align between that lint and the dartdoc requirement.
My gut feeling says that the lint should also cover libraries...

**Comment by rekire** [comment]
To simplify this issue: The output could suggest to use that lint warning. With that hint I would have not opened this issue.

**Comment by sigurdm** [comment]
Ah - of course - let's do that!

**Comment by isoos** [comment]
> To simplify this issue: The output could suggest to use that lint warning. With that hint I would have not opened this issue.

In itself such lint would not be enough to 1:1 mirror the current analysis, which has a threshold for reporting missing API docs (currently at 20%), as the lints would only return the missing ones, and we are missing the total count of API symbols.

However, if you are only interested in having **all** your API symbols documented, by all means use the lint, as it will give you the feedback much faster than running `dartdoc` as a separate process.

**Comment by rekire** [comment]
I had out of the box more then 20% I just aimed to have 100%. Might be also some hint of the `library;` statement would be nice ether. I was not aware of that keyword before I tried to get 100%.

**Comment by srawlins** [comment]
Sorry for my delayed response. I thought to myself "Could I implement this real quick in dartdoc? How would I do that?" And realized I should look into the warnings system. It turns out we have one warning in place: `no-library-level-docs`. I can't remember exactly now, but I think warnings are enabled with `dart bin/dartdoc.dart --warnings no-library-level-docs`.

Checks for docs for public API will probably be trickier, because of inheritance. 😬

**Comment by sigurdm** [comment]
Opened https://github.com/dart-lang/linter/issues/4962 for alignment on the lint. Closing this issue as I don't think we want to do more in pana.
