### ISSUE TITLE
Flag incorrect lower bounds in pubspec.yaml

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pana#1356]
(Filing based on offline discussion.)

It's incredibly easy to accidentally add usage of APIs that require a newer version of a dependency than the lower bound for that package. E.g., you originally add `some_package: ^1.0.0` when you start using it, and then a year later you do something new with `some_package` that was actually added in `1.1.0`. Unless you (the person adding the new API usage) happens to have a `pubspec.lock` that was created before the API was added, and hasn't been update since, everything will work fine. Standard CI is extremely unlikely to catch it, since CI generally tests in a clean environment.

In the flutter/packages repo we solved this by adding a CI step that runs `{dart/flutter} pub downgrade`, then `analyze`. (We actually need to remove dev dependencies first to make it more robust, but haven't implemented that yet.) It would be great to put that check into `pana` so that it was much more widespread (e.g., would show up in pub.dev scores; that's a bit late, but better than nothing since people can always retract).

**Comment by isoos** [comment]
This has been implemented and deployed to pub.dev.
