### ISSUE TITLE
Analyze packages with `resolution:workspace`.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pana#1369]
Related to https://github.com/dart-lang/pub/issues/4127

**Comment by sigurdm** [comment]
Either we

* Remove `resolution` and `workspace` sections from the pubspec before analyzing.
* Make a "dummy package" that depends on the package for resolution.

**Comment by jakemac53** [comment]
With workspaces effectively shipped in 3.5 stable (for Dart packages at least), should we prioritize work on this? I migrated the build/test repos to use workspaces, but just realized that means they won't get docs published for new versions.

**Comment by sigurdm** [comment]
https://pub.dev/packages/build_runner/score seems good now!
