### ISSUE TITLE
`localhost` urls do not have to be https

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pana#1371]
Currently we report a problem if README.md contains any http link. But for `localhost` http is fine.

See: https://staging.pub.dev/packages/appengine/score

![image](https://github.com/dart-lang/pana/assets/8613953/bc57e5c6-22c7-4968-8017-d7f21d541e37)

**Comment by isoos** [comment]
I would argue that this shouldn't be a `<a href="">` link, rather a code highlight. It is not that regular visitors are able to casually click on it and see a working page....
