### ISSUE TITLE
pana `dart format` failures should explain how to ignore generated files.

### ISSUE THREAD

**Issue by eseidel** [dart-lang/pana#1391]
e.g. https://pub.dev/packages/shorebird_code_push/versions/1.1.3/score

Says:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/d209d331-f09d-4028-91eb-7cedbdf712e0">

But doesn't say how to resolve the `dart format` issue:
https://github.com/dart-lang/pana/blob/3314a87d954d210430e56658024b36aa7de809f5/lib/src/report/static_analysis.dart#L202

In the case of generated files I suspect they should be excluded (as we have in the analysis_options.yaml):
https://github.com/shorebirdtech/updater/blob/75de37ccb36f2d495e7c187851c3229492f64114/shorebird_code_push/analysis_options.yaml#L5

I'm happy to make fixes to our package.  I'm mostly filing this issue so that future people who hit this won't end up confused?

**Comment by isoos** [comment]
We are using only the default `dart format .` command in this case, and I don't think it is considering the excludes in `analysis_options.yaml` (which in your case already excludes generated libraries).

I don't know if there is any plan for the dart format tool, but if that is not on its schedule, we may use the exclude patterns to filter out such files from the scoring and the report.

/cc @jonasfj

**Comment by eseidel** [comment]
I just republished.  Turns out we'd formatted but not republished.  So it may just be the error was on our side.

**Comment by sigurdm** [comment]
> In the case of generated files I suspect they should be excluded

I think we prefer formatting of the generated code before checking in/publishing.

Closing, as it seem this is easily doable by package authors.

Feel free to reopen if there is still a problem here.
