### ISSUE TITLE
Extension type instance variables in default constructors are marked as missing documentation

### ISSUE THREAD

**Issue by albertms10** [dart-lang/pana#1393]
Having extension type declarations [as such](https://github.com/albertms10/music_notes/blob/209d52d5fc4d2433111c08b1f06474f09401856f/lib/src/note/frequency.dart#L16):

```dart
/// Documented extension type.
extension type const Frequency._(num hertz) implements num { 
  // ...
}
```

leads to these warnings in the _Provide documentation_ section from Pub.dev analysis (see [`music_notes` score](https://pub.dev/packages/music_notes/versions/0.18.0/score) example):

![Pub.dev Provide documentation Pana](https://github.com/user-attachments/assets/8ff98ac9-290b-4bbe-9334-acdf76e0bd7d)

---

After looking into the code, it seems instance variables in extension type default constructors—which ATM cannot be documented at all—are not excluded from the list of symbols missing documentation.

https://github.com/dart-lang/pana/blob/3314a87d954d210430e56658024b36aa7de809f5/lib/src/dartdoc/index_to_pubdata.dart#L44-L55

**Comment by isoos** [comment]
Thanks for reporting this, we should add the exclusions!

**Comment by isoos** [comment]
I'm unsure if this is something dartdoc could fix, so I've filed https://github.com/dart-lang/dartdoc/issues/3829.

**Comment by sigurdm** [comment]
Closing in favor of https://github.com/dart-lang/dartdoc/issues/3830
