### ISSUE TITLE
Score support for swift package manager in plugins with ios/macos support

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pana#1402]
Reading:
https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors#how-to-add-swift-package-manager-support-to-an-existing-flutter-plugin

As far as I can tell we need to detect the presence of a `<plugin_name>/<platform>/Package.swift` file. Where platform is respectively `ios` and `macos` for the two platforms, or `darwin` that covers both.

I suggest we do an initial zero-scoring report note as we did for wasm support:

* If the package is an ios plugin:
  * if it has `<plugin_name>/ios/Package.swift` or `<plugin_name>/darwin/Package.swift` file, mark platform support as fully passing
   * otherwise write "in the future this will receive a reduced score, please migrate to Swift package manager (link)"
* Similarly for macos

**Comment by jonasfj** [comment]
How will `flutter_tool` behave if there is also a `podspec` file? Can there be conflicts or how does it work.

Just suggesting that this might also be worth checking.

**Comment by loic-sharma** [comment]
> How will `flutter_tool` behave if there is also a `podspec` file? Can there be conflicts or how does it work.

An iOS plugin can support _both_ CocoaPods and Swift Package Manager at the same time. In fact, that's what we [recommend](https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors#how-to-add-swift-package-manager-support-to-an-existing-flutter-plugin): 

> Flutter plugins should support both Swift Package Manager and CocoaPods until further notice.
>
> Swift Package Manager adoption will be gradual. Plugins that don't support CocoaPods won't be usable by projects that haven't migrated to Swift Package Manager yet. Plugins that don't support Swift Package Manager can cause problems for projects that have migrated.

Ideally, a plugin that supports both SwiftPM and CocoaPods shouldn't be penalized.

The proposal in the issue sounds good to me - please let me know if you have any questions!
