### ISSUE TITLE
git fatal: detected dubious ownership in repositor

### ISSUE THREAD

**Issue by dumabg** [dart-lang/pana#1404]
Pana stops to work, it gives error in the git command.

I've already done  git config --global --add safe.directory, but continues appearing the error.

```
2024-10-07 18:53:42.459803 WARNING: Flutter SDK path was not specified, pana will use the default Dart SDK to run `dart analyze` on Flutter packages.
2024-10-07 18:53:42.470774 INFO: Running `dart --version`...
2024-10-07 18:53:42.500316 INFO: Running `flutter --no-version-check --version --machine`...
2024-10-07 18:53:43.128042 INFO: Running `git rev-parse --show-toplevel`...
2024-10-07 18:53:43.137730 SHOUT: Problem analyzing 
                                  Failed to run `rev-parse --show-toplevel`.
                                  fatal: detected dubious ownership in repository at '/D/Projectes/lib/flutter/__pub_score_analysis/test_screen'
                                  To add an exception for this directory, call:
                                  
                                        git config --global --add safe.directory /D/Projectes/lib/flutter/__pub_score_analysis/test_screen
                                  #0      runGit (package:pana/src/tool/git_tool.dart:41:5)
                                  <asynchronous suspension>
                                  #1      withTempDir (package:pana/src/utils.dart:134:12)
                                  <asynchronous suspension>
                                  #2      runGitIsolated (package:pana/src/tool/git_tool.dart:52:10)
                                  <asynchronous suspension>
                                  #3      _detectGitRoot (package:pana/src/package_analyzer.dart:236:14)
                                  <asynchronous suspension>
                                  #4      PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:95:23)
                                  <asynchronous suspension>
                                  #5      withTempDir (package:pana/src/utils.dart:134:12)
                                  <asynchronous suspension>
                                  #6      main (file:///opt/pub-cache/hosted/pub.dev/pana-0.22.12/bin/pana.dart:225:19)
                                  <asynchronous suspension>

```

**Comment by sigurdm** [comment]
I think we run git commands without the local configuration for maximal reproducability:
https://github.com/dart-lang/pana/blob/3314a87d954d210430e56658024b36aa7de809f5/lib/src/tool/git_tool.dart#L22

I'm not sure exactly what the 'detected dubious ownership in repository at' message means.

Are you on windows?

Perhaps something can be learned from https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-reposit

**Comment by isoos** [comment]
> I think we run git commands without the local configuration for maximal reproducability

Yes, we create temp directories to hide all locally available configuration from the process, overriding `HOME` and the config file path for the `git` process. https://github.com/dart-lang/pana/blob/master/lib/src/repository/git_local_repository.dart#L51-L54

@dumabg: could you please share more details about your setup?

**Comment by dumabg** [comment]
I'm on Linux, but the project is in a Windows disk.

In the project, I haven't any problem with git.

**Comment by sigurdm** [comment]
I think you need to make sure that you own the files... 

From https://stackoverflow.com/a/73265433

> If the same problem occurs on [NTFS](https://en.wikipedia.org/wiki/NTFS)/Windows, make sure the parent folder of the .git and .git folder itself are both owned by the exact user you run git.exe from.
>
> Just the same group (Administrators) or changing only the parent may not work.

**Comment by sigurdm** [comment]
Not sure we are going to add support for custom git configuration.

**Comment by isoos** [comment]
> Not sure we are going to add support for custom git configuration.

I don't think we should. The repository verification is a proof that a clean system can access the repository and it contains what it claims to contain. Once we open up for custom configuration, this may not be true anymore.

**Comment by dumabg** [comment]
I've run with `sudo -u root env "PATH=$PATH" pana --no-warning` and it runs, but appears some warnings:

```
  Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
fatal: detected dubious ownership in repository at '/opt/flutter'
To add an exception for this directory, call:

        git config --global --add safe.directory /opt/flutter
2024-10-08 14:38:52.482832 WARNING: Flutter SDK path was not specified, pana will use the default Dart SDK to run `dart analyze` on Flutter packages.
2024-10-08 14:38:52.493764 INFO: Running `dart --version`...
2024-10-08 14:38:52.528551 INFO: Running `flutter --no-version-check --version --machine`...
2024-10-08 14:39:16.389305 WARNING: Unable to detect Flutter version.
                                    Exception: Unable to parse output as JSON:
                                    
                                    ```
                                    OUT:
                                    Resolving dependencies...
                                    Downloading packages...
                                      _fe_analyzer_shared 72.0.0 (75.0.0 available)
                                      analyzer 6.7.0 (6.10.0 available)
                                      browser_launcher 1.1.1 (1.1.2 available)
                                      collection 1.18.0 (1.19.0 available)
                                      coverage 1.8.0 (1.9.2 available)
                                      crypto 3.0.3 (3.0.5 available)
                                      dds 4.2.4+1 (4.2.7 available)
                                      devtools_shared 10.0.1 (11.0.0 available)
                                    [50 more lines]
                                    ERR:
                                    fatal: detected dubious ownership in repository at '/opt/flutter'
                                    To add an exception for this directory, call:
                                    
                                        git config --global --add safe.directory /opt/flutter
                                    Building flutter tool...
                                    Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log HEAD -n 1 --pretty=format:%ad --date=iso
                                    Standard out: 
                                    Standard error: fatal: detected dubious ownership in repository at '/opt/flutter'
                                    To add an exception for this directory, call:
                                    
                                    [3 more lines]
                                    ```
                                    
2024-10-08 14:39:16.392902 INFO: Running `git rev-parse --show-toplevel`...
2024-10-08 14:39:17.779258 INFO: Running `flutter --no-version-check pub pub get --no-example`...
2024-10-08 14:39:20.459353 INFO: Running `flutter --no-version-check pub pub get --no-example`...
2024-10-08 14:39:23.161283 SEVERE: `dart pub outdated` failed.
                                   fatal: detected dubious ownership in repository at '/opt/flutter'
                                   To add an exception for this directory, call:
2024-10-08 14:39:25.140069 INFO: Running `git init`...
2024-10-08 14:39:25.161364 INFO: Running `git remote add origin https://github.com/dumabg/test_screen`...
2024-10-08 14:39:25.168004 INFO: Running `git remote show origin`...
2024-10-08 14:39:25.937169 INFO: Running `git fetch --depth 1 --no-recurse-submodules origin master`...
2024-10-08 14:39:35.309369 INFO: Running `git ls-tree -r --name-only --full-tree origin/master`...
2024-10-08 14:39:35.322008 INFO: Running `git show origin/master:example/pubspec.yaml`...
2024-10-08 14:39:35.334314 INFO: Running `git show origin/master:pubspec.yaml`...
2024-10-08 14:39:39.252302 INFO: Analyzing pub downgrade...
2024-10-08 14:39:39.254409 INFO: Running `flutter --no-version-check packages pub downgrade --no-example`...
2024-10-08 14:39:41.224742 INFO: [pub-downgrade-error]
2024-10-08 14:39:41.225002 INFO: Resolving dependencies...
                                 fatal: detected dubious ownership in repository at '/opt/flutter'
                                 To add an exception for this directory, call:
                                 
                                        git config --global --add safe.directory /opt/flutter
                                 The current Flutter SDK version is 0.0.0-unknown.
                                 
                                 Because test_screen depends on isweb_test any which requires Flutter SDK version >=1.17.0, version solving failed.
                                 
                                 
                                 You can try the following suggestion to make the pubspec resolve:
                                 * Try using the Flutter SDK version: 3.24.3.
2024-10-08 14:39:41.227242 INFO: Running `flutter --no-version-check packages pub upgrade --no-example`...
```

**Comment by dumabg** [comment]
A simplest package:

 ```
Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
fatal: detected dubious ownership in repository at '/opt/flutter'
To add an exception for this directory, call:

        git config --global --add safe.directory /opt/flutter
2024-10-08 15:00:42.704826 WARNING: Flutter SDK path was not specified, pana will use the default Dart SDK to run `dart analyze` on Flutter packages.
2024-10-08 15:00:42.715844 INFO: Running `dart --version`...
2024-10-08 15:00:42.751344 INFO: Running `flutter --no-version-check --version --machine`...
2024-10-08 15:02:03.637659 WARNING: Unable to detect Flutter version.
                                    Exception: Unable to parse output as JSON:
                                    
                                    ```
                                    OUT:
                                    Resolving dependencies...
                                    Downloading packages...
                                      _fe_analyzer_shared 72.0.0 (75.0.0 available)
                                      analyzer 6.7.0 (6.10.0 available)
                                      browser_launcher 1.1.1 (1.1.2 available)
                                      collection 1.18.0 (1.19.0 available)
                                      coverage 1.8.0 (1.9.2 available)
                                      crypto 3.0.3 (3.0.5 available)
                                      dds 4.2.4+1 (4.2.7 available)
                                      devtools_shared 10.0.1 (11.0.0 available)
                                    [50 more lines]
                                    ERR:
                                    fatal: detected dubious ownership in repository at '/opt/flutter'
                                    To add an exception for this directory, call:
                                    
                                        git config --global --add safe.directory /opt/flutter
                                    Building flutter tool...
                                    Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log HEAD -n 1 --pretty=format:%ad --date=iso
                                    Standard out: 
                                    Standard error: fatal: detected dubious ownership in repository at '/opt/flutter'
                                    To add an exception for this directory, call:
                                    
                                    [3 more lines]
                                    ```
                                    
2024-10-08 15:02:03.641077 INFO: Running `git rev-parse --show-toplevel`...
2024-10-08 15:02:04.037447 INFO: Running `flutter --no-version-check pub pub get --no-example`...
2024-10-08 15:02:15.543602 INFO: Running `flutter --no-version-check pub pub get --no-example`...
2024-10-08 15:02:15.912373 INFO: Running `flutter --no-version-check pub pub outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...
2024-10-08 15:02:17.047286 SEVERE: `dart pub outdated` failed.
                                   Unable to parse output as JSON:
                                   ```
2024-10-08 15:03:30.773442 INFO: Running `git init`...
2024-10-08 15:03:30.792192 INFO: Running `git remote add origin https://github.com/dumabg/isweb_test`...
2024-10-08 15:03:30.799998 INFO: Running `git remote show origin`...
2024-10-08 15:03:41.581757 INFO: Running `git fetch --depth 1 --no-recurse-submodules origin master`...
2024-10-08 15:03:43.089321 INFO: Running `git ls-tree -r --name-only --full-tree origin/master`...
2024-10-08 15:03:43.109539 INFO: Running `git show origin/master:example/pubspec.yaml`...
2024-10-08 15:03:43.130792 INFO: Running `git show origin/master:pubspec.yaml`...
2024-10-08 15:03:49.712980 INFO: Analyzing pub downgrade...
2024-10-08 15:03:49.714510 INFO: Running `flutter --no-version-check packages pub downgrade --no-example`...
2024-10-08 15:03:51.925730 INFO: Running `dart analyze --format machine lib`...
2024-10-08 15:03:52.318176 INFO: [pub-downgrade-error]
                                 Exception: Analysis failed with unexpected output.
                                 `fatal: detected dubious ownership in repository at '/opt/flutter'`
                                 #0      parseCodeProblem (package:pana/src/code_problem.dart:65:5)
                                 #1      PackageContext._staticAnalysis.<anonymous closure> (package:pana/src/package_context.dart:301:23)
                                 #2      MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
                                 #3      NonNullsIterator.moveNext (dart:_internal/iterable.dart:921:20)
                                 #4      SetBase.addAll (dart:collection/set.dart:58:23)
                                 #5      _Set.addAll (dart:collection-patch/compact_hash.dart:986:11)
                                 #6      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:192:27)
                                 #7      Iterable.toSet (dart:core/iterable.dart:513:21)
                                 #8      PackageContext._staticAnalysis (package:pana/src/package_context.dart:303:12)
                                 <asynchronous suspension>
                                 #9      PackageContext.downgradeAnalysisErrorMessage.<anonymous closure> (package:pana/src/package_context.dart:203:24)
                                 <asynchronous suspension>
                                 #10     trustworthyDependency.downgrade (package:pana/src/report/dependencies.dart:228:21)
                                 <asynchronous suspension>
                                 #11     trustworthyDependency (package:pana/src/report/dependencies.dart:254:28)
                                 <asynchronous suspension>
                                 #12     createReport (package:pana/src/report/create_report.dart:41:30)
                                 <asynchronous suspension>
                                 #13     PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:210:20)
                                 <asynchronous suspension>
                                 #14     PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:98:14)
                                 <asynchronous suspension>
                                 #15     withTempDir (package:pana/src/utils.dart:134:12)
                                 <asynchronous suspension>
                                 #16     main (file:///opt/pub-cache/hosted/pub.dev/pana-0.22.12/bin/pana.dart:225:19)
                                 <asynchronous suspension>
                                 
2024-10-08 15:03:52.320330 INFO: Running `flutter --no-version-check packages pub upgrade --no-example`...

## ✓ Follow Dart file conventions (30 / 30)
### [*] 10/10 points: Provide a valid `pubspec.yaml`

### [*] 5/5 points: Provide a valid `README.md`

### [*] 5/5 points: Provide a valid `CHANGELOG.md`

### [*] 10/10 points: Use an OSI-approved license

Detected license: `BSD-3-Clause`.


## ✗ Provide documentation (10 / 20)
### [x] 0/10 points: 20% or more of the public API has dartdoc comments

Dependency resolution failed, unable to run `dartdoc`.

### [*] 10/10 points: Package has an example


## ✓ Platform support (20 / 20)
### [*] 20/20 points: Supports 6 of 6 possible platforms (**iOS**, **Android**, **Web**, **Windows**, **macOS**, **Linux**)

* ✓ Android

* ✓ iOS

* ✓ Windows

* ✓ Linux

* ✓ macOS

* ✓ Web

### [x] 0/0 points: WASM compatibility

Unable to detect compatibility with runtime `wasm`, and this package will not be rewarded full points in a future version of the scoring model.

See https://dart.dev/web/wasm for details.


## ✗ Pass static analysis (0 / 50)
### [x] 0/50 points: code has no errors, warnings, lints, or formatting issues

* Running `flutter pub outdated` failed with the following output:

```
Unable to parse output as JSON:
```
```


## ✗ Support up-to-date dependencies (0 / 40)
### [x] 0/10 points: All of the package dependencies are supported in the latest version

* Could not run `flutter pub outdated`: Unable to parse output as JSON:

```
OUT:
{
  "packages": [
    {
      "package": "characters",
      "kind": "transitive",
      "isDiscontinued": false,
      "isCurrentRetracted": false,
      "isCurrentAffectedByAdvisory": false,
      "current": {
        "version": "1.3.0"
[127 more lines]
ERR:
fatal: detected dubious ownership in repository at '/opt/flutter'
To add an exception for this directory, call:

        git config --global --add safe.directory /opt/flutter
```

### [x] 0/10 points: Package supports latest stable Dart and Flutter SDKs

* Found no Flutter in your PATH. Could not determine the current Flutter version.

### [x] 0/20 points: Compatible with dependency constraint lower bounds

downgrade analysis failed with:
Analysis failed with unexpected output.
`fatal: detected dubious ownership in repository at '/opt/flutter'`

Run `flutter pub downgrade` and then `flutter analyze` to reproduce the above problem.

You may run `dart pub upgrade --tighten` to update your dependency constraints, see [dart.dev/go/downgrade-testing](https://dart.dev/go/downgrade-testing) for details.


Points: 60/160.
```

**Comment by dumabg** [comment]
My final solution is copy the code to linux and run pana in it.

**Comment by sigurdm** [comment]
I think that is a fine workaround in this case.
