### ISSUE TITLE
Detect if dependency is in pubspec but not used in libraries.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#152]

**Comment by kevmoo** [comment]
Yup. This goes in the bucket of tooling alignment.

`pub` does this already. We should have the code in one place...

**Comment by robbecker-wf** [comment]
Feel free to take inspiration from https://github.com/Workiva/dependency_validator/blob/master/lib/dependency_validator.dart#L163
Workiva has written dependency_validator that checks for:

Missing: When a dependency is used in the package but not declared in the pubspec.yaml
Under-promoted: When a dependency is used within lib/ but only declared as a dev_dependency.
Over-promoted: When a dependency is only used outside lib/ but declared as a dependency.
Unused: When a dependency is not used in the package but declared in the pubspec.yaml.

**Comment by kevmoo** [comment]
That's awesome, @robbecker-wf !

We should also look at https://github.com/dart-lang/pub/blob/master/lib/src/validator/strict_dependencies.dart and rationalize these implementations

**Comment by isoos** [comment]
Couple of updates:

- `package:dependency_validator`: it is geared toward a specialized CLI tool:
  - lacks the option to specify the working dir
  - does not expose the analysis results programmatically,
  - has some opinionated output, eg. assumes `analyzer` dependency is for running `dartanalyzer` (not  showstopper, but worth to note)

- `pub` has a different set of issues:
  - it is not published on pub, depending on a git repo is not the best example we can set
  - it looks hard to extract validation logic into a separate package, because it relies on the "know the world" pub-specific `Entrypoint` class and other dependencies
  - It looks like the dependency validation should be part of the output in `pub publish --dry-run`, but I was not able to get it on the output.

As we have the data already processed, I think we are better of to do this in our codebase.

**Comment by sigurdm** [comment]
I think this should be implemented in the analyzer. That way pana would get it "for free" when it runs analysis. Opened https://github.com/dart-lang/sdk/issues/53735
