### ISSUE TITLE
License detection doesn't work if license text has comment prefixes

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pana#155]
A lot of flutter packages have 'unknown' license, e.g.:
https://pub.dartlang.org/experimental/packages/video_player

This seems to be happening when (for historical reasons) license files have each line start with // ?
https://github.com/flutter/plugins/blob/master/packages/video_player/LICENSE

**Comment by kevmoo** [comment]
@mit-mit Fix your license file! 😄 

...we can look into this, too...

CC @isoos

**Comment by isoos** [comment]
I offered to fix this, because detecting license text in a source code requires similar pre-processing of the license file. It is not much code: if the license file starts with '//', then we'll split it to lines, remove the '//' prefixes, and join it back.
