### ISSUE TITLE
Classify package in more error cases

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#165]
https://analyzer-dot-dartlang-pub.appspot.com/packages/box2d/0.3.0/5665683559940096

Seems we should still be able to figure out the platform...

**Comment by kevmoo** [comment]
@isoos – why do we need to block platform classification if there are errors?

Just want to understand...

**Comment by isoos** [comment]
> why do we need to block platform classification if there are errors?

I thought that it is better to be strict and whitelist the errors that we think are safe. % of false positives vs. false negatives. We could remove it if you think the other way would provide more benefits.

**Comment by kevmoo** [comment]
Also error_code "ARGUMENT_TYPE_NOT_ASSIGNABLE"
