### ISSUE TITLE
Ignore errors for files in 'lib/src' that aren't used "visible" files

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#167]
See https://analyzer-dot-dartlang-pub.appspot.com/packages/firebase

Firebase has code in `lib/src/assets` that we want to share between /test and /example.

It's not imported/exported by anything in lib/bin.

Causing the score to be low.

Worth handling?

**Comment by kevmoo** [comment]
Thoughts, @isoos ?

**Comment by isoos** [comment]
We'd need to track the transitive deps of every public API library, and if a given asset is not a dependency from any of those, we could ignore the errors in the health score. But it is still distributed with the package and usable for client of that package, which I'd track as a different maintenance issue (dart file in src/ is not being used) and penalize a bit.

**Comment by kevmoo** [comment]
My work-around: https://github.com/firebase/firebase-dart/commit/f701036e2c9898bd481a3f88e49676f86466211d
