### ISSUE TITLE
should handle better when version cannot be resolved

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#18]
e.g. in package:unittest, we get the following error:

```
ERR : Package test has no versions that match >=0.12.4 <0.12.5 derived from:
    | - unittest depends on version >=0.12.4 <0.12.5
```

**Comment by kevmoo** [comment]
We should just add a special-case for unittest that pins the version `< 0.12.0`

**Comment by isoos** [comment]
This could happen with any package, we should rather detect and report it.
