### ISSUE TITLE
Allow running pana on a pub server that isn't pub.dartlang.org

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/pana#180]
# Problem
Workiva runs our own internal pub server due to IP concerns. Pana looks to have hard-coded the main pub server here: 
https://github.com/dart-lang/pana/blob/master/lib/src/download_utils.dart#L22

This means that we can't currently run it to analyze packages hosted on our internal server. I'd like to see a command-line parameter to specify the pub server to use.

On a related note: It should probably also handle sub dependencies declared in pubspec.yaml that are hosted on a different pub server.

**Comment by robbecker-wf** [comment]
@kevmoo ping

**Comment by kevmoo** [comment]
Ack. Pull requests welcome, @robbecker-wf !

**Comment by kevmoo** [comment]
@robbecker-wf – this landed with https://pub.dartlang.org/packages/pana/versions/0.8.0

Let us know how it works!

**Comment by robbecker-wf** [comment]
@kevmoo  Worked pretty well. It runs to completion and I got JSON output, but somehow it seemed to stick to PUB_HOSTED_URL when generating suggestions and couldn't find a public package (async in this case) because it was using the wrong server and should have used pub.dartlang.org

Example snippet:
```
 "suggestions": [
  {
   "level": "error",
   "title": "Fix dependencies in `pubspec.yaml`.",
   "description": "Running `pub upgrade` failed with the following output:\n\n```\nERR: Could not find package async at https://pub.workiva.org.\n Depended on by:\n - pub itself \n```\n"
```

**Comment by isoos** [comment]
How are you using `pub get` / what is in your `pubspec.yaml` for referencing private and public projects?

**Comment by robbecker-wf** [comment]
Public packages are generally just given a version or range. Internal packages are referenced with the full server info. 

Example pubspec:
```
dependencies:
  some_other_internal_package:
    hosted:
      name: some_other_internal_package
      url: https://pub.workiva.org
    version: ^2.0.0
  args: '>=0.13.7 <2.0.0'
```

I ran pana like so: `PUB_HOSTED_URL=https://pub.workiva.org pana an_internal_package`

**Comment by isoos** [comment]
Though. @kevmoo: any idea how to resolve this?

**Comment by kevmoo** [comment]
> Though. @kevmoo: any idea how to resolve this?

Yup! We need to ditch the `PUB_HOSTED_URL` logic and add an option to specify the server

Then the first download uses the server – and pub uses the `hosted` args in the downloaded package to do the right thing.

`PUB_HOSTED_URL` is sent to the pub client, too – which means it's ignoring the `hosted` bit of the pubspec (it seems)

**Comment by kevmoo** [comment]
`add an option` – meaning `--pub-server-host` or similar

**Comment by kevmoo** [comment]
@robbecker-wf – if you're bored, would you sync down the latest from github and try it out?

I think we fixed it!

**Comment by kevmoo** [comment]
@robbecker-wf – you can just do `pub global activate --source git https://github.com/dart-lang/pana` if you like

...just don't forget to deactivate and update to the shipped version when we publish 😄

**Comment by robbecker-wf** [comment]
Hmm I'm not seeing it work on my end. I like the command line arg approach though. 
I've tried it installed directly from github and via a local clone of master. I've run it with various different ways of writing the option and it doesn't seem to use it for the initial load of the requested package. I don't know if it would have worked for dependent package loads since it exits at that point.
```
pub global activate --source git https://github.com/dart-lang/pana
pana --hosted-url=https://pub.workiva.org w_viewer
FINE       Running `/usr/local/Cellar/dart/1.24.2/libexec/bin/dart --version`...
INFO       Downloading package w_viewer latest
FINE       Running `/usr/local/Cellar/dart/1.24.2/libexec/bin/pub cache add --verbose w_viewer`...
SHOUT      Problem with pkg w_viewer
           ERR : Could not find package w_viewer at https://pub.dartlang.org.
```
Notice it's still trying to use pub.dartlang.org. What am I doing wrong?

These all still go to pub.dartlang.org:
```
pana --hosted-url=https://pub.workiva.org w_viewer
pana --hosted-url https://pub.workiva.org w_viewer
pana --hosted-url pub.workiva.org w_viewer
pana w_viewer --hosted-url=https://pub.workiva.org
```

**Comment by kevmoo** [comment]
We just published this as 0.8.1

the URL should be http(s)://your_host_here

will look again

**Comment by robbecker-wf** [comment]
It's a modifed clone of https://github.com/dart-lang/pub-dartlang-dart

**Comment by isoos** [comment]
Could you please double check the download URL for me? `pana` uses the following pattern: `/packages/$package/versions/$version.tar.gz`, it may be that yours doesn't support it yet.

**Comment by robbecker-wf** [comment]
Yep. That path style works on our pub server.

**Comment by isoos** [comment]
I think I know what is happening: you need to specify the version too in order to get the specific download to work. Could you please give it another got? (0.8.2 was released, it should work, and no need for sourcing it from github)

**Comment by robbecker-wf** [comment]
I used version 0.8.2 and it works when specifying the --hosted-url , package name, and version! 
Although if I don't specify a version it does not work and the error shows the incorrect pub server url:

```
SHOUT      Problem with pkg w_viewer
           ERR : Could not find package w_viewer at https://pub.dartlang.org.
```

**Comment by isoos** [comment]
@robbecker-wf: we've published a new `pana` version, and it will make it clear that you need to specify the version.
