### ISSUE TITLE
Run Locally / More info on health?

### ISSUE THREAD

**Issue by brianegan** [dart-lang/pana#202]
Hello, thanks for all the work on pana! Great tool :)

Goal: I have a project at 90 health, I want 100!

Problem: I looked at a project with a perfect score (100), copied the analysis options over to my own project, fixed any analysis issues that came up, and published a new version.

But my score remained at 90 😢 

Questions:

  * Is it possible to run pana against a local project to determine the score? I don't want to spam users with minor version increases just to check if I was successful at improving the score.
  * Is it possible to get more information on *why* the health score isn't at 100 or document additional reasons (beyond the analysis options) that might cause lower health? I've looked through the output of pana, but the files report no erors or dartfmt issues.
  * After reading through how fitness is calculated, I think I found the problem: I had two `dev_dependencies` with the `any` version constraint. However, this isn't mentioned in the docs on the Pub site (only analysis options is discussed), is not reported by the pana tool's output, and I had to read through the code itself to find this check: https://github.com/dart-lang/pana/blob/deb087e75e5e581427049e11a1068bc00f30fce6/lib/src/fitness.dart#L121

Thanks for your help!

**Comment by isoos** [comment]
What is the package name? I could take a quick look on the full analysis data.

Also: have you tried to use the analysis-options from here: https://pub.dartlang.org/help#health
If there is an ambiguity, please copy the results here.

> Is it possible to run pana against a local project to determine the score?

You can run locally: https://github.com/dart-lang/pana#use-as-an-executable
The health score is a simple division of the fitness scores, we could add it to the output of course.

> I had two dev_dependencies with the any version constraint. However, this isn't mentioned in the docs on the Pub site (only analysis options is discussed), is not reported by the pana tool's output, and I had to read through the code itself to find this check.

Yeah, that is not reported yet. I think we shall remove the devDependancies penalties from the score, as it doesn't influence the package when it is imported.

**Comment by brianegan** [comment]
Thanks for the info!

"You can run locally: https://github.com/dart-lang/pana#use-as-an-executable"

I'm able to run pana on my machine, but is it possible to *run pana against a local project*? e.g. I have package with a `pubpsec.yaml` sitting on my filesystem, and I would like pana to analyze that package. 

That way I can make changes, run pana, and verify I've improved the health score. In addition, I could also add `pana` to my CI server (Travis, Gitlab, Jenkins) so it checks the overall score and would fail if the `health` score goes down.

It seems pana always tries to download the package from the given `--hosted-url`.

**Comment by isoos** [comment]
Ah, I see. The library has a method that runs `pana` against a local directory, but we don't expose it through the binary (I thought we do, but apparently we don't).

I've added #203 to track the dev_dependencies related scoring, and #204 to track the command line parameter to expose it.

**Comment by isoos** [comment]
@brianegan: we've published a new version, and you should be able to run it locally via

```
pana [<options>] --source path <directory>
```

The devDependency-related penalty has also changed. Let us know if you have further issues.

**Comment by brianegan** [comment]
Cool, thanks so much!
