### ISSUE TITLE
Remove pubspec.lock validation?

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#207]
`pubspec.lock` contains all dependencies, including the `dev_dependencies`. Right now we validate the list of its contents against the parsed output of `pub upgrade`, but at the same time we remove `dev_dependencies` from the `pubspec.yaml` file, there is a potential mismatch of these two.

@kevmoo: shall we remove the validation?

**Comment by kevmoo** [comment]
Uh. It's purely redundant? I guess so...
