### ISSUE TITLE
Add suggestion around examples

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#208]
See https://github.com/dart-lang/pub-dartlang-dart/blob/1ca93dcb1d1e1489bec4768de553b9091974cc58/app/lib/shared/utils.dart#L226

This helper should be moved to pana and used to suggest folks add an example to their package.

Then the pub site can use the same logic. Magic!

**Comment by isoos** [comment]
Different kinds of suggestion would be helpful here:
- the package has no examples
- the package has files in the example directory, but not with recognized pattern
- the package has a recognized example, but seems to be too short or too long

**Comment by kevmoo** [comment]
Yup!
