### ISSUE TITLE
Files that import .template.dart files that are generated by Angular produce failures in Strong Mode analysis.

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pana#213]
Example:
https://pub.dartlang.org/packages/angular_components/versions/0.9.0-alpha%2B2#-analysis-tab-

The `uri_has_not_been_generated: ignore` option I have in the `analysis_options.yaml` file is not being used. https://github.com/dart-lang/angular_components/blob/master/analysis_options.yaml#L8

**Comment by kevmoo** [comment]
We use our own `analysis_options.yaml` file in pana – so folks can't just ignore all errors and skip our checks.

In-file ignores are your only option – now.

**Comment by isoos** [comment]
I'd argue the case that similarly to generated files for `json_serializable`, `.template.dart` files could be included in the package sources.

**Comment by kevmoo** [comment]
Ah! You'd think so, but in this case we're dealing w/ more than just
boilerplate code.

This is very different than json_serializable

**Comment by nshahan** [comment]
@kevmoo So users can still avoid pana's check in this instance by placing the ignores everywhere they need them.

I'd propose that since this practice can be common, and will be required in the updated angular boostrapping it might make sense to allow that particular analysis option from the package to override pana's setting.

**Comment by matanlurey** [comment]
I agree with this being ignored in the default `pana` settings.

It won't hurt other customers.

**Comment by isoos** [comment]
> This is very different than json_serializable

How so?

**Comment by kevmoo** [comment]
> How so?

The generated templates are a product of the top-level package/app. They need to be synced w/ the version of angular, etc.

**Comment by kevmoo** [comment]
@matanlurey @nshahan – RE `uri_has_not_been_generated` – I think it's fine to whitelist some analysis options that can pass through. This is a good example.

@isoos – happy to chat/VC if you want more info

**Comment by isoos** [comment]
Is there a build process that generates these files? Maybe we could run standardized builds before analysis (that cannot be used to mess up with the analyzer environment).

**Comment by nshahan** [comment]
In this case the files are generated by angular when building the project.

**Comment by isoos** [comment]
> In this case the files are generated by angular when building the project.

`pana` could trigger that build before analysis.

**Comment by kevmoo** [comment]
> pana could trigger that build before analysis.

@isoos – there is no "build" for components. The build is part of an app.

**Comment by nshahan** [comment]
I am still seeing these errors when I publish new version of the package:
https://pub.dartlang.org/packages/angular_components/versions/0.9.0-alpha%2B5#-analysis-tab-

**Comment by isoos** [comment]
@nshahan thanks for flagging it again! We've had an embarrassing bug in `pana`, will be fixed with https://github.com/dart-lang/pana/pull/248 which will be part of the 0.10.2 release.
