### ISSUE TITLE
Handle dependency_overrides

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#242]
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides suggest that dependency overrides are allowed to help local development, while the package can be published with an official set of dependencies.

We don't ignore the overrides and analyse the package as if it was a local copy, e.g. in https://pub.dartlang.org/packages/build_resolvers#-analysis-tab-

**Comment by jakobr-google** [comment]
Should we always just ignore them, though? A dependency override can also be used to pin a transitive dependency to a specific version, if needed.

**Comment by isoos** [comment]
> A dependency override can also be used to pin a transitive dependency to a specific version, if needed.

I think if the published package needs a specific dependency version, it should do it through a dependency constraint, and not as an override of the same constraint.

It is useful for a non-published library or app, but I think the analysis should use the same dependency range as a regular pub client.
