### ISSUE TITLE
qrcode_reader is given a score of 93, despite being reported as not building

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pana#294]
https://pub.dartlang.org/packages/qrcode_reader

https://groups.google.com/d/msg/flutter-dev/hg2y0x0GiQE/ThFFeoK9BgAJ

Whatever signal we're missing is clearly an important one. :)  @mit-mit

**Comment by eseidelGoogle** [comment]
Feel free to dupe this one way or the other.  But I suspect this will be a growing problem.  As our ecosystem grows, folks are going to depend on pub more to separate the working things from the broken ones.

**Comment by sigurdm** [comment]
Closing as obsolete
