### ISSUE TITLE
having non-dart files (maybe .md, .txt?) as candidates to display under the 'Example' tab? 

### ISSUE THREAD

**Issue by bcko** [dart-lang/pana#329]
In https://github.com/dart-lang/pana/blob/fb06d872f31b2c38bc8e4e4a94056378065a0971/lib/src/maintenance.dart#L35L44

```dart
/// Returns the candidates in priority order to display under the 'Example' tab.
List<String> exampleFileCandidates(String package) => [
      'example/lib/main.dart',
      'example/main.dart',
      'example/lib/$package.dart',
      'example/$package.dart',
      'example/lib/${package}_example.dart',
      'example/${package}_example.dart',
      'example/lib/example.dart',
      'example/example.dart',
    ];
```
Currently only Dart files can be displayed under the 'Example' tab. While looking at published packages, I found some examples are more suitable to describe in non dart files. (ex. command line programs). Is it possible to include non-dart file (maybe `example/example.md` or `example/example.txt`) additionally? Thank you!

**Comment by isoos** [comment]
`example.md` sounds okay, I'm just not sure whether it should be `example/example.md`, `example/README.md` or something else in the root directory? Do we have a project where something like this already exists?

**Comment by isoos** [comment]
I've sampled the most popular packages and a few small ones that I had in mind, and the pattern I see the following:

In the simpler cases, parts of the code in the `example` directory is repeated in the `README`.

When the library gets complex, the `example` directory gets more and more sub-directories. At the same time, the `README` will provide links to these directories, and/or provide links to blogs, wiki or other articles.

I fear that how it is handled will vary between project maintainers, and at this point it seems to be premature to commit to one pattern. I'll close this as this won't be worked on for now, but feel free to re-open if there is a more concrete use-case where this could help.
