### ISSUE TITLE
Update messages

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#360]
- [ ] s/general direction API/general direction of the API/g?
- [ ] s/you to detect bugs/you detect bugs/g
- [ ] s/earlier.Start/earlier. Start/g
- [ ] 'Fix analysis and formatting errors|hints|errors and hints

**Comment by sortie** [comment]
Also: "Strong mode helps you to detect bugs and potential issues earlier.Start your analysis_options.yaml file with the following:"

The 'to' is not needed AFAIK and a space is missing between 'earlier.' and 'Start'.
