### ISSUE TITLE
Parse known reason of tool errors and log them at lower log level.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#368]
- [x] pub upgrade:
  - [x] `pub upgrade` failed. ERR: Because <pkg> depends on <whatever> which doesn't exist (unknown SDK "unittest"), version solving failed.
  - [x] `Because split_panel depends on logging_handlers >=0.5.0+2 which requires SDK version >=0.5.0+1.r21823 <2.0.0, version solving failed.`
- [x] Failed dartfmt Error: Exception: dartfmt on bin/ failed with exit code 65 Could not format because the source could not be parsed.
- [x] `pub upgrade` failed. ERR: Git error.

**Comment by isoos** [comment]
Current known patterns are covered.

**Comment by sortie** [comment]
I'll take a look at the logs again after the next deployment with this new pana and look for additional issues.
