### ISSUE TITLE
Set health/fitness score to zero when dartanalyzer or dartfmt fails

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#369]
- `dartanalyzer` failure: https://pub.dartlang.org/packages/shuffler#-analysis-tab-
- `dartfmt` + `dartanalyzer` failure: https://pub.dartlang.org/packages/protractor_dar#-analysis-tab-

**Comment by sortie** [comment]
dartfmt fails as in the source doesn't parse, surely not that the code isn't dartformatted?

**Comment by isoos** [comment]
> dartfmt fails as in the source doesn't parse, surely not that the code isn't dartformatted?

It doesn't parse (likely too old). Otherwise `dartfmt` completes and we have the list of files that are not formatted.
