### ISSUE TITLE
Pana probably shouldn't suggest formatting generated code?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pana#385]
https://pub.dartlang.org/packages/flutter_inapp_purchase#-analysis-tab-
<img width="709" alt="screen shot 2018-08-08 at 10 55 17 am" src="https://user-images.githubusercontent.com/11857803/43855223-ce1615fa-9af9-11e8-983f-07674977f0c8.png">

And/or we should fix things like package:intl to generate formatted code?
https://github.com/dart-lang/i18n/issues/186

**Comment by isoos** [comment]
From a consumer point of view, a generated code with errors or warnings has the same importance as a non-generated code with errors or warnings. I think the same can be applied to formatting too.

**Comment by mit-mit** [comment]
@eseidelGoogle as a temporary measure, can't whatever script which is invoking codegen just invoke autoformatting next?

**Comment by zoechi** [comment]
Most code generation uses build which does format the code as far as I remember.
`intl` is one of the few exceptions.

**Comment by eseidelGoogle** [comment]
Any resolution is fine. :)  But if I'm understanding this bug correctly it sounds like if you want to internationalize your package and get a perfect score on pub you have to do extra work.  Not a huge deal, but seems like a relatively common use case.  I guess the recommended solution is to chase dart-lang/intl#181?

**Comment by isoos** [comment]
If the code generator uses an old version of the `dart_style` it could produce a slightly mis-formatted output. I see code generation as an explicit part of the development process (e.g. not hidden behind some magic that happens), and if the tool doesn't format properly, the caller of the generator should also call the `dartfmt` after each run, as if they were writing the code by hand in the first place.

**Comment by sigurdm** [comment]
I think for now we will just insist on generated code being formatted.

The issue whether we should suggest formatting code at all is a different case.
