### ISSUE TITLE
Homepage and Documentation issues and suggestions don't make sense.

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pana#386]
I'm seeing messages like: 

Homepage is not helpful.
Update the homepage property: create a website about the package or use the source repository URL.

Documentation URL is not helpful.
Update the documentation property: create a website about the package or remove it.

For packages that supply homepage and documentation links. 

https://pub.dartlang.org/packages/angular#-analysis-tab-
https://pub.dartlang.org/packages/angular_components#-analysis-tab-

**Comment by isoos** [comment]
Ah, because `angular` points to `webdev.dartlang.org`, while we consider `*.dartlang.org` as not helpful. We'll need to make an exception with angular there.
