### ISSUE TITLE
"Description is too short"

### ISSUE THREAD

**Issue by brianegan** [dart-lang/pana#416]
Is there any better metric to ensure a meaningful description is present? I get this error on a lot of my packages, but a lot of the time it doesn't actually make sense to add a longer description. 

For example, my package "font_awesome_flutter" reads "The Font Awesome Icon pack available as Flutter Icons." Nice and short, describes what the package provides, and doesn't contain extraneous information.

But, that description costs me 20 points on the "Maintenance" score because it's shorter than 60 characters. Just wanted to open this to get a discussion going and maybe understand a bit more the perspective from the team working on Pub / determining these metrics.

**Comment by brianegan** [comment]
Sounds good -- just wanted to provide some user feedback as it's something I've noticed on a lot of my packages. 

Overall, I completely agree it's hard to set a "better number," since what I'm asking for is more subjective. Thanks for the discussion!

**Comment by MrCsabaToth** [comment]
Can the message "The package description is too short." be more specific and tell that 60-180 by any chance?
