### ISSUE TITLE
Is Pana flutter only?

### ISSUE THREAD

**Issue by shamblett** [dart-lang/pana#418]
Its handy to check my packages with pana before publishing, however if I try this I get 

WARNING    Unable to detect Flutter version.
           ProcessException: The system cannot find the file specified.

Seems as though you need a flutter installed, the package is marked as Flutter,Other so I assumed it would work ina VM environment but it seems not to.

**Comment by isoos** [comment]
@shamblett: It does not require Flutter for analysing non-Flutter packages, although the environment scan will try to detect it and it will log its failure. But if the package does not require Flutter then the analysis should go on.

When I run pana, I get this:

```
INFO       Running `flutter --version --machine`...
WARNING    Unable to detect Flutter version.
           ProcessException: No such file or directory
             Command: flutter --version --machine
           #0      runProc (package:pana/src/utils.dart:41:17)
           <asynchronous suspension>
           #1      ToolEnvironment.getFlutterVersion (package:pana/src/sdk_env.dart:230:15)
           <asynchronous suspension>
           #2      ToolEnvironment._init (package:pana/src/sdk_env.dart:60:31)
           <asynchronous suspension>
           #3      ToolEnvironment.create (package:pana/src/sdk_env.dart:115:19)
           <asynchronous suspension>
           #4      PackageAnalyzer.create (package:pana/src/package_analyzer.dart:62:54)
           <asynchronous suspension>
           #5      main (file:///Users/isoos/work/google/pub/pana/bin/pana.dart:144:46)
           <asynchronous suspension>
           #6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
           #7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
INFO       Downloading package [xxx] latest
```

As you can see, the warning does not block the analysis, and it goes on to download the package. If the analysis is blocked for you, there should be another reason for it, could you please share the full console output?

> the package is marked as Flutter,Other so I assumed it would work ina VM environment but it seems not to.

In this case the "Other" category means that it could be running in a console application, which may be a server, a regular app, or part of a code generator toolchain. Unfortunately we don't distinguish between those yet, hence the "other" category.

**Comment by shamblett** [comment]
Ok, I think were getting there, when I run 

pana --source path .

for my package on linux its all Ok, on Windows however I get this 

INFO       Parsing pubspec.yaml...
INFO       Running `C:\dev\dart\dart-sdk\bin\dartfmt --dry-run --set-exit-if-changed C:\dev\dart\projects\sporran\lib`...
CreateProcessW failed 2
SEVERE     `dartfmt` failed.
           ProcessException: The system cannot find the file specified.
           
             Command: C:\dev\dart\dart-sdk\bin\dartfmt --dry-run --set-exit-if-changed C:\dev\dart\projects\sporran\lib
           ProcessException: The system cannot find the file specified.

If I run the commands at the command line, for instance 

C:\dev\dart\dart-sdk\bin\dartfmt --dry-run --set-exit-if-changed C:\dev\dart\projects\sporran\lib

they work OK,

**Comment by isoos** [comment]
@shamblett: could you please help me out with windows debugging? What is the output when you run this dart code:

```
import 'dart:io';

void main() {
  final pr = Process.runSync(r'C:\dev\dart\dart-sdk\bin\dartfmt', [
    '--dry-run',
    '--set-exit-if-changed',
    r'C:\dev\dart\projects\sporran\lib',
  ]);
  print(pr.exitCode);
  print(pr.stdout);
  print(pr.stderr);
}
```

**Comment by shamblett** [comment]
Yes no problem,

Output of the above code on my Windows(10) box ...

C:\dev\dart\dart-sdk\bin\dart.exe  --enable-asserts --enable-vm-service:64438 C:\dev\dart\projects\sporran\example\pana_test.dart
Observatory listening on http://127.0.0.1:64438/

CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: C:\dev\dart\dart-sdk\bin\dartfmt --dry-run --set-exit-if-changed C:\dev\dart\projects\sporran\lib
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:485:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:631:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      main (file:///C:/dev/dart/projects/sporran/example/pana_test.dart:4:22)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Process finished with exit code 255

**Comment by isoos** [comment]
I see. What happens if you change it to `.exe`, e.g.:
```
final pr = Process.runSync(r'C:\dev\dart\dart-sdk\bin\dartfmt.exe', [
```
or rather, what are the files in the `C:\dev\dart\dart-sdk\bin` directory? (Sorry, I have no access to a windows machine at the moment).

**Comment by shamblett** [comment]
They are all .bat files except for the dart.exe itself. Changing the code to use ...\dartfmt.bat gives 

C:\dev\dart\dart-sdk\bin\dart.exe --enable-asserts --enable-vm-service:65074 C:\dev\dart\projects\sporran\example\pana_test.dart
Observatory listening on http://127.0.0.1:65074/

1
src\lawndart\src\indexeddb_store.dart
src\Sporran.dart
src\SporranDatabase.dart

Process finished with exit code 0

so this seems to work, looks like from a cmd console windows works out if a file is executable and just runs it whereas Process.runSync needs the full file extension.

**Comment by isoos** [comment]
@shamblett thanks, we can certainly detect the existence of the `.bat` or the `.exe` files and use them when they are present. I may ask you to validate intermediate versions if that's ok with you.
