### ISSUE TITLE
Packages with a minimum bound 2.1.0-dev.XX of the SDK fail on pub upgrade

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pana#435]
See:
https://pub.dartlang.org/packages/angular_components#-analysis-tab-
https://pub.dartlang.org/packages/angular#-analysis-tab-
https://pub.dartlang.org/packages/angular_forms#-analysis-tab-

**Comment by isoos** [comment]
This issue was moved to dart-lang/pub-dartlang-dart#1738
