### ISSUE TITLE
Redesign: "Support Dart 2 in pubspec.yaml."

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#448]
We have the following suggestion in packages where the SDK constraint does not support 2.0:

<img width="638" alt="screen shot 2018-11-19 at 8 34 11" src="https://user-images.githubusercontent.com/4778111/48692370-1012db00-ebd6-11e8-9a15-eaec94002060.png">

This was designed for package with constraints of e.g. `<2.0`, but it also includes packages that have a constraint of `>=2.1 <3.0`.

Couple of options:
- We remove this, as pre-2.0 is legacy, and they won't get analyzed, and such message won't be displayed anyway.
- We increase the limit to always match the latest stable. Couple of options:
  - We specify the latest stable to check for.
  - We introduce a fake version of 2.9999, and if a constraint supports it, we are happy.
  - We check for 2 minor versions up the currently used SDK (e.g. 2.0 will check for 2.2).

/cc @mit-mit @jonasfj - any preference there?

**Comment by sortie** [comment]
I suggest we show this unless the package SDK constraint allows any version after 2.0.

We should have another warning if the package doesn't allow the latest stable release "Support Dart X.Y in pubspec.yaml".

**Comment by sortie** [comment]
On second thought, we should turn this into a general package issue if the package doesn't allow the latest Dart SDK in the 2.X series.
