### ISSUE TITLE
Consider using pedantic as a baseline for linting?

### ISSUE THREAD

**Issue by pq** [dart-lang/pana#459]
Currently there's a hand-crafted list of enforced lints:

https://github.com/dart-lang/pana/blob/master/lib/src/analysis_options.dart

It would be cool to migrate to the [pedantic package](https://pub.dartlang.org/packages/pedantic) rule-set and be able to badge projects "pedantic" clean or something.  

FWIW we're tagging pedantic and flutter user lints now in the generated docs [like so](https://dart-lang.github.io/linter/lints/avoid_empty_else.html):

![image](https://user-images.githubusercontent.com/67586/49875993-3d1e6c00-fdd7-11e8-9de3-80dfc04a7d49.png)

(The flutter badge corresponds to lints in flutter user options.)

/cc @isoos @kevmoo @jonasfj

**Comment by pq** [comment]
fyi @davidmorgan

**Comment by isoos** [comment]
We had similar discussion a few months back, and I agree with @mit-mit's comment [here](https://github.com/dart-lang/pana/issues/312#issuecomment-395358825): "If we think this flag is high value, why is it not on by default [in dartanalyzer]?"

Copying and applying Flutter's defaults is fine, we also try to match stagehand's defaults, but other than that, these lints are optional, and we should treat them as such. If they provide better code quality, then their place is in `dartanalyzer`.

**Comment by pq** [comment]
I guess that raises the question then of why lint at all.  FWIW I don't think the rules provided as an example in the stagehand template were very thoughtfully considered (and needless to say I'm certain they are not being actively maintained or reviewed).  As for @mit-mit's comment, I think analyzer flags are a little different than lints but I totally agree with the sentiment.  Many lints are lints (and not hints / warnings) for mainly historical reasons.  Someday we may get around to rationalizing what is where but that's a conversation that's started and ultimately stalled at least a few times in the last 5 years (@bwilkerson: or more?).

As another thought, what if being pedantic clean earned you extra credit in scoring? 😉

**Comment by isoos** [comment]
> https://github.com/dart-lang/stagehand/blob/master/analysis_options.yaml

I meant the ones that are created by default in the simple project template:
https://github.com/dart-lang/stagehand/blob/master/templates/package-simple/analysis_options.yaml

The goal is that if a developer follows the recommended tool's defaults, we should gave it the max score.

**Comment by pq** [comment]
Ah, right.  Good point.  In that case my original thought is actually little more relevant.  The rules in that template haven't been changed for over a year.

![image](https://user-images.githubusercontent.com/67586/49894238-51c42980-fe02-11e8-80c4-b98abe332759.png)

> The goal is that if a developer follows the recommended tool's defaults, we should gave it the max score.

Regarding this, if `pedantic` compliance isn't something we want to count in the score, could we still consider some kind of a vanity badge?  As these are the emerging Google Dart standards, I think it would be good reinforcement if we called them out somehow.

Thanks for the back and forth!

**Comment by jonasfj** [comment]
I like the idea of a vanity badge :)

**Comment by pq** [comment]
> I like the idea of a vanity badge :)

#463

fyi @mit-mit

**Comment by pq** [comment]
Cycling back to this, as of https://github.com/dart-lang/stagehand/pull/594, stagehand is now using `package:pedantic` for all of its templates. 🤘 

Can we update `pana` to follow suit?

**Comment by kwalrath** [comment]
We haven't quite updated stagehand yet... I'll prepare a release so we can publish it.

**Comment by isoos** [comment]
Sure, we shall follow that.

**Comment by kwalrath** [comment]
And the doc change is finally out! I'll publish stagehand by tomorrow morning.
