### ISSUE TITLE
Suggest removal of print statements

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#461]
At least in flutter libraries people shouldn't be printing stuff, example of something that was released:
https://github.com/dooboolab/flutter_calendar_carousel/blob/825df5e8c1e5224972776efc1ed5e0047fa6cf04/lib/flutter_calendar_carousel.dart#L718

Maybe we could come up with a rule for this...?

Note. we should probably still support CLI libraries that needs to print stuff.

**Comment by pq** [comment]
> I'm wondering: can this be a linter rule?

👍 

Disallowing calls to `print` would be straight-forward and there's lots of precedent (e.g., https://eslint.org/docs/rules/no-console, `pylint`'s `"print-statement"`, etc).  

There's an open request here:https://github.com/dart-lang/linter/issues/88.  More motivation there welcome!

**Comment by isoos** [comment]
This was implemented as a lint, and it is up to the package's author to use it.
