### ISSUE TITLE
Line lengths other than default of 80 fail formatting check

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/pana#468]
Files formatted using dartfmt with a line length other than the default of 80 are marked as unformatted.

Can pana support these other line lengths?

I see that the [Dart style guide](https://www.dartlang.org/guides/language/effective-dart/style#avoid-lines-longer-than-80-characters) and [dart_style's readme](https://github.com/dart-lang/dart_style#using-dartfmt) both discourage line lengths other than 80, but does that mean they're prohibited? If so, why are they an option in dartfmt? Doesn't that go against [its philosophy of being non-configurable](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it)?

**Comment by isoos** [comment]
`pana`'s goal is to keep to the defaults and official recommendations as much as possible. The style guide's wording ("strongly encouraged to keep the default line length of 80 columns") is a clear indication of the preferences there, and for the public packages on `pub.dartlang.org` we'd like to keep that standard (and follow the style guide if it changes).

If your request is for private packages, and running `pana` on them with configurable line length: we can support using a specified line length. Would you be interested in that?

**Comment by greglittlefield-wf** [comment]
That makes sense, thanks for the answer!

I was asking for public packages, making sure that the 80 column rule was going to be in place for the foreseeable future before I update packages to use 80 😄.

We don't yet run `pana` on our private packages, but I think having the line length configurable would be a nice feature, since we do have a couple private packages on which we'd like to keep using 100/120 columns.

**Comment by isoos** [comment]
@greglittlefield-wf this has been released in `pana` `0.12.10`, you can use the `--line-length` CLI option.

**Comment by greglittlefield-wf** [comment]
Awesome, thank you!!
