### ISSUE TITLE
`pub upgrade` failed. STDERR exceeded 100000 lines.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#49]
Not much in the logs. It was for `twit 0.0.4`.

**Comment by thosakwe** [comment]
@isoos I just want to mention that `twit` is buggy when sending `POST` requests. Not sure if that has anything to do with it.

**Comment by isoos** [comment]
It looks like the version resolver goes berserk, and dumps a lot of output. It eventually succeeds, but goes over the current limit of `100 000` lines, thus we drop those information.

**Comment by kevmoo** [comment]
I wanted to keep the log to aid debugging.

We could make a circular log and only keep the last 10,000 lines (or something) and just make it time based?

**Comment by isoos** [comment]
The only thing that we seem to get out of the verbose logs whether there is a version conflict. That doesn't seem to worth to store MB+ logs to keep around, when for most debugging purposes we can just re-run the analysis and see what's going on.

I'd rather reduce the verbosity to a manageable level and extract what we are interested in.

**Comment by kevmoo** [comment]
Sure...another issue was being able to capture if/how we have IO errors.

The latest version of the SDK "does the right thing here", though.
