### ISSUE TITLE
get pana score from cli?

### ISSUE THREAD

**Issue by pq** [dart-lang/pana#503]
Is there an easy easy way to get the score for a package when running the command line interface?

**Comment by pq** [comment]
In addition to local package maintenance, we're also looking at doing experiments across pub package code bases to do things like gauge API change impacts.  To help focus our analysis it would be great if we could sort on pana score (or otherwise query it).

**Comment by pq** [comment]
Just seeing #514; cheers for taking a look @isoos!

**Comment by isoos** [comment]
@pq There is an unofficial pub API that exposes the scores, e.g.:
- https://pub.dartlang.org/api/packages/http/metrics?pretty
- https://pub.dartlang.org/api/packages/http/metrics?pretty&reports

**Comment by pq** [comment]
Oh!  For the second use case this is fantastic.  (In that case we don't want to have to run `pana` ourselves.)

Cheers @isoos!

**Comment by isoos** [comment]
#514 has been published with `pana` `0.12.14`

**Comment by pq** [comment]
Many thanks @isoos!

**Comment by pq** [comment]
Thanks again for doing this.  I've added a bot that does some baseline checking for the linter.

https://github.com/dart-lang/linter/pull/1464

I'll be interested to see how useful this regular feedback is.  (Or whether the baseline, currently just "health" and "maintenance" scores, should be more granular.)
