### ISSUE TITLE
Don't penalize a package without an example if there is also no public API

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#510]
Examples:
- https://pub.dartlang.org/packages/devtools
- https://pub.dartlang.org/packages/peanut

**Comment by kevmoo** [comment]
See also https://github.com/dart-lang/pub-dartlang-dart/issues/2047

**Comment by isoos** [comment]
I'm not 100% convinced that no public API should exempt a package from the same standards as other packages have:
- I could use a resource from the `lib/` directory.
- I could use an internal class from the `lib/src` directory.
- I could one or more script from the `bin/` directory.

There is one exemption though we should probably do: if the `README.md` has a non-empty section with the title `Example` or `Usage` (or similar), we don't require to have a separate example file.

**Comment by kevmoo** [comment]
> I'm not 100% convinced that no public API should exempt a package from the same standards as other packages

I think the examples I have at the top are pretty valid. You could say if there is no content outside of `lib/src`. Folks should NOT be having anyone depend on internal classes from `lib/src` – that's a pretty hard recommendation.
