### ISSUE TITLE
Idea: warn if the package archive contains documentation

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#521]
The root cause of https://github.com/dart-lang/pub-dartlang-dart/issues/2104 is that the package archive contains the documentation, e.g.  in [this directory](https://github.com/VictorRancesCode/flutter_dialogflow/tree/master/doc/api/v2_message/QuickReplies) both lowercase and uppercase `quickReplies.html` is present.

Besides the chance of name collision of Windows filesystem, it is an extra content that should not be part of the package (e.g. most users won't check and see the documentation that way).

Should we add e.g. a -30 penalty for it? /cc @jonasfj

**Comment by jonasfj** [comment]
No, I think it's better to warn when publishing in `pub` client... It should be easy to check if the `doc/api/` folder contains an `index.html` file...

This is something people want to notice before they publish :) hehe

**Comment by jonasfj** [comment]
Actually, @sigurdm, thoughts? :) hehe

**Comment by sigurdm** [comment]
Ideally I think we should not be able to commit (or at least warn when we try) from an unclean git repo.
That would help on this as well.

**Comment by sigurdm** [comment]
I think we should also warn (when publishing) about docs as jonas suggested.
And the warning could have a suggestion to add something nice to your .gitignore.
