### ISSUE TITLE
Unnecessary additional *.g.yaml file isn't deleted from analyzed package.

### ISSUE THREAD

**Issue by YevhenKap** [dart-lang/pana#522]
Why file `pedantic_analizys_option_[digits].g.yaml` doesn't autodelete after analyzing package? I am using a full list of [linter options](https://dart-lang.github.io/linter/lints/options/options.html). But in the created file part of these are just duplicated. 
Pana version 0.12.14.

**Comment by jonasfj** [comment]
I think we should fine a way to run analysis without having to mutate the package :)

**Comment by isoos** [comment]
> Why file pedantic_analizys_option_[digits].g.yaml doesn't autodelete after analyzing package?

Yeah, it looks like we are not deleting it, should be an easy fix.

> I think we should fine a way to run analysis without having to mutate the package :)

We have too many complex rules around `analysis_options.yaml` to consider them to be added as command-line options to `dartanalyzer`.
