### ISSUE TITLE
Update readme to include points for pedantic lints

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#524]
The pub site references https://pub.dartlang.org/documentation/pana/latest/

But this site does not list the set of lints that's checked.

It's tough to figure out what's required here: https://pub.dartlang.org/packages/kernel/versions/0.3.15#-analysis-tab-

**Comment by isoos** [comment]
I'm wondering: shouldn't we detect that the `analysis_options.yaml` differs from our version (e.g. misses pedantic, or uses a Flutter-related version that is outdated), and give hints to users? That way we would be notifying the users at the right place (on the analysis tab).

**Comment by isoos** [comment]
This is no longer relevant.
