### ISSUE TITLE
limit the amount that hints can contribute to a package's score

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pana#545]
`package:analyzer_plugin` has a score of 47 on the package site: https://pub.dev/packages/analyzer_plugin#-analysis-tab-.

Most of that is due to the health score, where we get an overall score of 0. And much of that score is due to an overall -500 score from 2 hints, primarily the `Prefer using /// for doc comments.` hint.

I think we should limit the amount that either:
- any one hint can contribute to the score (-5 total?)
- or, that hints overall can contribute to the score (-5 total?)

Generally, I think that errors and warnings should contribute much more to the score than hints.

(Separately, we may want to remove the `slash_for_doc_comments` lint from the package score, as it doesn't necessarily indicate much about the health or quality of the API of the package).

**Comment by isoos** [comment]
Interesting suggestion, and I can see the appeal. However, speaking about the general rule: why should the penalties be the same for a package that has 1500+ linter issues and a package with 10 linter issues? From the point of a consumer of the given packages, while debugging and reading the code, I will have 150x the chance that the code I'm reading differs from the suggested standards.

I understand that it is a lot of code to migrate, but you can get yourself an exemption with the `// ignore_for_file: rule_name` linter comment at the beginning of the given files. (Note: I have plans to expose such exemptions in the future, although probably not with the same amount of penalty as your totals are now).

If you are questioning the necessity of the specific lint, you'll need to file a PR against https://github.com/dart-lang/pedantic/blob/master/lib/analysis_options.1.8.0.yaml#L29, as we are just following `pedantic`'s rules.

**Comment by devoncarew** [comment]
> why should the penalties be the same for a package that has 1500+ linter issues and a package with 10 linter issues? 

Instead of linter issues, I think we should focus on info/warning/error level issues. A package with actual analysis errors should not score as well as one without errors. `package:analyzer_plugin` has no analysis errors (or warnings), yet receives a -500 point score for the info level issues. I think there should be a max cap on what the info level issues can contribute, in order to better measure the relative health of the package.

> you'll need to file a PR against https://github.com/dart-lang/pedantic/blob/master/lib/analysis_options.1.8.0.yaml#L29, as we are just following pedantic's rules.

I'm starting to question whether we should mandate the use of package:pedantic on all packages. It's google's internal rule set; useful to encourage people to look at, but not necessarily mandate that they use. Instead we could:
- just use the analyzer's default errors and warnings, or
- use the analysis_options.yaml file defined by the package itself

**Comment by kevmoo** [comment]
I'm absolutely sympathetic to the concern here.

It'd probably be more work, but many limit the total negative points for "style" lints? http://dart-lang.github.io/linter/lints/

**Comment by isoos** [comment]
> I'm starting to question whether we should mandate the use of package:pedantic on all packages.

I think so far the reception of using `pedantic` was good, and some of its rules (e.g. `unawaited_futures`) have a good potential to catch bugs and improve the overall code quality. `pedantic` is part of the official guides and also part of `stagehand`'s templates. It is opinionated, but as every new package is encouraged to use it, most developers won't have problems with it.

It also follows the [official style guides](https://dart.dev/guides/language/effective-dart/documentation#do-use--doc-comments-to-document-members-and-types) as you can see it has a suggestion to use `///` for documentation. I think the set of tools and the official guides are in-sync with using `pedantic` as a quality measure on the pub site.

**Comment by isoos** [comment]
> It'd probably be more work, but many limit the total negative points for "style" lints?

We have a similar mechanism: files that are not formatted according `dartfmt` take a penalty of 1 hint / per file (regardless of the lines that need the formatting). Similarly, we could treat style lints per file, and not per-incident. Assuming ~60 files/incidents present in `analyzer_plugin`, the package would still receive `-26` health score.

**Comment by sigurdm** [comment]
I don't have strong opinions on this.
I agree warnings should ideally be taken more seriously than hints, but I see the value in striving towards a familiar and uniform style - people do read source code (for example when clicking 'go to definition' in the editor).

**Comment by klavs** [comment]
Considering the recent reactions to pedantic v1.9.0, I'd like to suggest that package is analyzed using the package's own `analysis_options.yaml` rules (using pedantic as a fallback) to evaluate it's consistency.

In addition to evaluation of consistency, the package should also be evaluated by how aligned it's `analysis_options.yaml` are to pedantic, by using some weighted comparison.

Such approach would give pana the ability steer the community in the right direction.
Let's take `prefer_single_quote` as an example. It was added to pedantic v.1.9.0 because that's the style Google uses internally. Here, pana would be able to assign weight of `0` for any violation of this rule, because it has zero impact on the quality of the package.
Now, let's assume the Dart team decides to throw double quotes out of the language. Here, pana would be able to assign some heavy weight `W` to the rule, because it's important for the community to move to the latest Dart version.

This way the community can still benefit from Google's internal experience (expressed as pedantic) and deviate from it when it makes sense to the package author.

**Comment by isoos** [comment]
>  I'd like to suggest that package is analyzed using the package's own `analysis_options.yaml` rules (using pedantic as a fallback) to evaluate it's consistency.

The goal of package analysis is not only to check whether the package has an obvious bug, but also to communicate to others, how it follows to the now-current established standards (which change over time). This includes bug-free, well-structured and formatted code (incl. style linter rules), presented in the proper project structure. 

While we could always analyse a package with 3 different ruleset (including the author-supplied rules), or in another context with different SDK versions, the question boils down to: how should we communicate it? If we use the author-provided rules, it means that we check if they were following their own standards. For the package's current and future users it provides more value to check whether the package follows the now-current standards.

I agree that it would be great if new rules would have a gradual increase in weight, unfortunately we don't have that yet.

**Comment by isoos** [comment]
This was implemented for a while, but not longer relevant with the new scoring.
