### ISSUE TITLE
`>=2.0.0-dev <3.0.0` constraints result in "not Dart 2 compatible"

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/pana#549]
This is possibly related to https://github.com/dart-lang/pana/issues/542. Consider the case of the package `angel_jael`, where the SDK constraint is `>=2.0.0-dev <3.0.0`. Whereas before the package could get a score, now it is marked as completely incompatible with Dart 2 (it actually is), and consequently is hidden from search results.

Is the new minimum version `2.0.0`? I can imagine that there might be many other packages that have a v2 dev version as their minimum.

**Comment by isoos** [comment]
IIRC some of the `2.0.0-dev` versions did have breaking changes while reaching `2.0.0`, and SDK after `2.0.0` assumes that `2.0.0-dev` is incompatible. Using `>=2.0.0' is the correct way to describe that you support 2.0.
