### ISSUE TITLE
Consider cyclomatic complexity as part of the health score.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#550]
An implementation of such analysis:
https://github.com/daniel-v/codemetrics

**Comment by pq** [comment]
cc @bwilkerson who might have some thoughts based on experience implementing similar metrics for Java back in the day...

**Comment by jonasfj** [comment]
Note. I like this idea, but we have plenty of metrics we score on, let's make those better and explain them better before we add opaque metrics like this.

**Comment by eernstg** [comment]
A good measure might be

```
weighted_average_of_complexity_metrics / inherent_complexity_of_problem
```

It wouldn't be particularly helpful to systematically punish every package that solves a complex problem, and it might not be possible to write solutions to complex problems with low complexity metrics. Now we just need a really robust and reliable way to measure the inherent complexity of the problem. ;-)

**Comment by sigurdm** [comment]
Personally I think the complexity metrics are cool, but way to subjective to start scoring packages on.

Maybe we can use it in other ways.

**Comment by jonasfj** [comment]
we're not planning to do this.
