### ISSUE TITLE
Please add example in the Readme on how to run

### ISSUE THREAD

**Issue by icatalud** [dart-lang/pana#558]
I had difficulties getting pana to analyze my package. The readme is not straightforward enough.

The instructions say that it can run by doing:
- "pana [<options>] --source path <local directory>"

However the only way I got pana to run in my local directory was:
- "pub global run pana --source path ."

Additionally, the "--source path" is non intuitive (at least to me), since initially I thought "path" was the directory. I suggest giving an example to make it easier for the user to understand.

**Comment by haarts** [comment]
I, too, thought `path` was the directory. But it turned out of be literally the string 'path' (or 'hosted'). Took me a while.

**Comment by Kaushl2208** [comment]
Hey @jonasfj, It seems like a good fix to start with. Can I work on it?

**Comment by jonasfj** [comment]
Sure feel free to improve the documentation.

**Comment by sigurdm** [comment]
Today you can run 
* `dart run pana path/to/project`
*  Or `dart global run pana path/to/project` if globally activated 
*  or `pana path/to/project` if globally activated, and `$PUB_CACHE/bin` is in your path.

This more or less reflects the readme
