### ISSUE TITLE
Pubspec parsing error returns scores of 100

### ISSUE THREAD

**Issue by axel-op** [dart-lang/pana#564]
On this line: https://github.com/dart-lang/pana/blob/master/lib/src/package_analyzer.dart#L127, 
when a pubspec file cannot be found or parsed, health and maintenance scores are both returned with a value of 100. 

This is because a `Summary` widget is returned with null `maintenance` and `health` fields, so the `_calculateScore` function (https://github.com/dart-lang/pana/blob/master/bin/pana.dart#L213) automatically set these two scores to 100.

**Comment by axel-op** [comment]
Another thing is that the penality of 100.0 given [on this line](https://github.com/dart-lang/pana/blob/master/lib/src/maintenance.dart#L141) is never applied because this suggestion is added to the "general" suggestion list and not to the maintenance suggestion list. And no score is calculated based on this "general" suggestion list.

**Comment by isoos** [comment]
Ah, good points here. Curious: do you know about a package on pub that has this?

**Comment by axel-op** [comment]
@isoos Not at all, I'm sorry.
