### ISSUE TITLE
Don't consider a package Flutter-only because of a flutter key in its pubspec

### ISSUE THREAD

**Issue by simolus3** [dart-lang/pana#570]
We're publishing a package using `dart:ffi` that works on the Dart VM or with Flutter. For Flutter users, we're including a special `build.gradle`/`Podspec` to include the native libraries used by the package. This only exists for convenience - the package works without Flutter if the shared library is available.
For the Flutter tool to pick up our native buildscripts, we need to have the `flutter.plugin` key set in our pubspec, so we're just doing this:
```yaml
flutter:
  plugin:
    foo: bar
```
Again, our library doesn't depend on the Flutter SDK or any Flutter-only package.

When running pana, we get
```json
"components": [
  "flutter",
  "io"
],
"uses": {
  "flutter": "used",
  "web": "forbidden",
  "other": "conflict"
},
```
And pub only gives us the "Flutter" label.

Can the rules be updated to handle a case like this? I imagine that this could happen more often now that ffi is stable in Dart 2.6. Ideally I'd like pub to also add the "Other" label and pana to use `pub upgrade` instead of `flutter packages upgrade` when running.

**Comment by jonasfj** [comment]
If already published what is the package? Then we can see source and pubspec :)

Are you sure you don't have an SDK constraint on Flutter?

**Comment by jonasfj** [comment]
Note. I'm that I'm sure we could fix it either way... The "Dart plugins" solution isn't exactly well-defined at this stage.

**Comment by simolus3** [comment]
This is the [pub link](https://pub.dev/packages/moor_ffi) of the package. Source and pubspec are available [here](https://github.com/simolus3/moor/blob/master/moor_ffi/pubspec.yaml).

I can live with the missing "Other" tag, but the combination of pana misidentifying this as a Flutter package and Flutter not supporting Dart 2.6 are reducing the "Health" score from 100 to 0.

**Comment by jonasfj** [comment]
hmm, seems like there is no constraint on the `Flutter` SDK... so maybe we shouldn't classify it that way in the future.

I think that is what will happen with the new classification spec we're working on.

**Comment by simolus3** [comment]
Interesting, thanks! Are there any public resources on the updated classification spec at this time?
I can understand that adding a bogus flutter key to the pubspec is pretty hacky and can break tooling like pana. But it'd be great if such use case could be supported. Maybe there could be something like a `flutter.toolingOnly` property informing pana that flutter is not used as a dependency?

**Comment by simolus3** [comment]
The warning on pubs are gone now, so I assume it's fixed. Thanks!
