### ISSUE TITLE
Let's remove LibraryScanner overrides

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#58]
(1) The override in its current form is misleading, because it creates a `dart:web_safe_io` package which doesn't exists, but somebody may think it does. A `dart-trusted:http` would be a more adept name.

(2) I think having these overrides is a bad precedent, for the following reasons:
- We don't want to keep track all of the libraries that use `dart:io` in a web-safe way. Getting onto that list, changing it would require efforts on all sides.
- We may track a few, but forget about it. As the libraries, change, some of these information gets outdated, even in a breaking way, and provides misleading results.
- Tracking `package_resolver`'s `http` use is an ever worse precedent: are we going to list everything there that has `http` as its dependency?

The correct solution: analyze the Dart sources and detect, whether the client is going to use any of the non-web-related `dart:io` code, and mark it as such. This a lot of effort, and probably not worth it at the moment.

The optimistic solution: let's assume that when both `dart:html` and `dart:io` is present, it is importing it in a web-safe-io way. We already have tests for this: https://github.com/dart-lang/pana/blob/master/test/platform_test.dart#L83

I'd go with optimistic solution, and remove the overrides altogether.

**Comment by isoos** [comment]
I'm trying to handle [this test](https://github.com/dart-lang/pana/blob/master/test/end2end/http_data.dart#L13) in a better way. The correct expression is that it may work everywhere, as long as you:
- don't call `new Client()`, and
- don't call any of the top-level `get`, `post`, ... `readBytes` methods, and
- none of the libraries you depend upon do any of these.

So, instead of claiming that it works everywhere, maybe we should claim that it may work everywhere. More closely: along the `worksOnWeb` flag, we could also have a `mayWorkOnWeb` flag, and the `description` could be `web?` instead of `web`.

That would turn that test assert into `flutter, server, web?`, which I think is more closer to the truth, and it is more generic, than the current hand-picked overrides.

I'm going to submit a PR with this soon.

**Comment by isoos** [comment]
Another side-effect overrides had was that they were masking the use of `dart:collection`, `dart:convert`... (see #59 test changes). While they may not be that interesting this time, I'd rather have them listed explicitly, then hiding them because a web platform has a special rule.

**Comment by isoos** [comment]
Another, more "taking the middle ground" option on this: let's only rewrite the `dart:io` dependency to `dart-web-safe:io` (or similar) for a curated/whitelisted cases. That way we the use of `dart:collection` and other libraries are not lost, while we can distinguish `dart:io` and `dart-web-safe:io`.

**Comment by kevmoo** [comment]
+1
