### ISSUE TITLE
Integrate the new tagging with scoring

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pana#589]
We should

- tag flutter plugins with the tags they declare
- penalize inconsistencies between declared platforms and those we detect

**Comment by jonasfj** [comment]
A) So if a package has `flutter.plugin.platform.web` the package should get the `platform:web` tag, even if the primary library imports `dart:io`.

However, if the primary library imports `dart:io` we do want to give it a penalty for claiming to support `web`.

This is only for Flutter plugins, other packages do not have a way to declare what platforms they support.

B) However, a package has a library that imports both `dart:io` and `dart:js`, that is if the a package has a any library with conflicting imports, then we should reflect this in scoring.
