### ISSUE TITLE
dart:cli is not classified as dart/native runtime

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#594]
- original report: https://github.com/dart-lang/pana/issues/591#issuecomment-568308868
- package: https://pub.dev/packages/dshell
- source code reference: https://github.com/bsutton/dshell/blob/master/lib/src/util/waitForEx.dart
- pana log: 
```
dshell-1.0.22 does not support dart with runtime: native-aot because of import violation at: [
package:dshell/dshell.dart,
package:dshell/src/util/string_as_process.dart,
package:dshell/src/util/pipe.dart,
package:dshell/src/util/runnable_process.dart,
package:dshell/src/util/waitForEx.dart,
dart:cli
]

dshell-1.0.22 does not support dart with runtime: native-jit because of import violation at: [package:dshell/dshell.dart, package:dshell/src/util/string_as_process.dart, package:dshell/src/util/pipe.dart, package:dshell/src/util/runnable_process.dart, package:dshell/src/util/waitForEx.dart, dart:cli]

```

**Comment by bsutton** [comment]
Do we have an eta on when this will be pushed to pub.dev?
My package is still being penalised due to this bug.

https://pub.dev/packages/dshell

**Comment by isoos** [comment]
@bsutton  We are planning to do a new pub release in the next few days, should be out before the end of the week.

**Comment by PietechSolution** [comment]
@isoos  

Looked like we face the same issue with our package too: https://pub.dev/packages/getflutter

We waiting for fix then we check if anything we need to do from our side.

Thanks.

**Comment by bsutton** [comment]
Thanks

**Comment by PietechSolution** [comment]
@bsutton looked like your package is fine, Did you did anything or issue fixed by dart-pana team

As we still facing this issue with our module: https://pub.dev/packages/getflutter 

Thanks.

**Comment by isoos** [comment]
@PietechSolution: In cases like this pub re-runs the analysis when a new pub release rolls out (e.g. when we upgrade pana), and there is no need for the package developers to update the package.

In case of `package:getflutter` the issue seems to be different than it was for `dshell`, I'll need to investigate what's going on...

**Comment by PietechSolution** [comment]
Thanks @isoos  

Please review once you get the time and if anything required from our side we will update it.

**Comment by isoos** [comment]
@PietechSolution: Your issue will be tracked via #605, I'm closing this now.
