### ISSUE TITLE
Make stats section optional

### ISSUE THREAD

**Issue by JFreakDK** [dart-lang/pana#600]
Have an option to not include the stats section in the json output like `--no-scores` for not including the stats section.

This is the section in the output:
``` 
"stats": {
  "analyzeProcessElapsed": 12743,
  "formatProcessElapsed": 2413,
  "resolveProcessElapsed": 26107,
  "totalElapsed": 59053
 },
```
The use-case is that if that section is not included a diff with the previous output file is enough to detect if a change to the code and/or dependencies is detected by the tools used by `pana`.

**Comment by isoos** [comment]
@JFreakDK: I wouldn't recommend relying on exact string matching, as it would break every time a dependency of your packages changes versions (e.g. if there is a new release of `package:http` if you rely on it).

Instead, the list of `"health"/"suggestions"` and `"maintenance"/"suggestions"` would be more indicative: if there was a change in that list, it is likely to have effect on the score on pub.dev.

**Comment by JFreakDK** [comment]
That is fair. For our use-case we would actually like to detect if there is a new dependency. We would not use it for pub.dev published extension, but to keep an eye on our app when we are not actively developing new features for the app. We would like to be able to keep an eye on changes to our dependencies so that we know if we should update something. For now I can create a utility that can remove the stats section before comparing the output.

**Comment by jonasfj** [comment]
You could alos use `pub upgrade -dry-run` to check for new dependencies.

@JFreakDK, just curious, would dependabot integration work for your use-case?

**Comment by JFreakDK** [comment]
The output from `pub upgrade -dry-run` looks better for a diff comparison.
Maybe a combination between `pub upgrade -dry-run` and the scores from pana could be a good indicator of the state of our app.
 
dependabot looks cool but currently our repo is not hosted at Github.
