### ISSUE TITLE
Tag and analysis failure for packages that have no dart files

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#604]
There are packages with resources only, e.g. `package:bulma_min`.

Updated: fixed package name.

**Comment by tenhobi** [comment]
Hi, any progress on this? I can see that `package:bulma` (https://pub.dev/packages/bulma) already got those flags back, but, for example, `package:effective_dart` (https://pub.dev/packages/effective_dart) still has `[UNDEFINED]`, and therefore `No valid SDK. (-20 points)`.

**Comment by isoos** [comment]
@tenhobi: I've just realized that my example was `bulma_min` instead of `bulma`. The later has an actual .dart file in it.

**Comment by isoos** [comment]
Also affected: [package:strict_dart](https://pub.dev/packages/strict_dart). (#632)

**Comment by vr19860507** [comment]
I temporary added some dart code to fix the problem!
