### ISSUE TITLE
Crash when analyzing pusbpec with no version field

### ISSUE THREAD

**Issue by axel-op** [dart-lang/pana#607]
The command `stagehand package-simple` generates a package where the `version` field of the pusbpec is commented out. 
When launching an analysis with pana, a `NoSuchMethodError` is thrown [at this line](https://github.com/dart-lang/pana/blob/master/lib/src/maintenance.dart#L459) with the message `The getter 'major' was called on null` because of this.

**Comment by acoutts** [comment]
I had this error as well and just submitted this PR to fix it: https://github.com/dart-lang/build/pull/2671

**Comment by sigurdm** [comment]
This is not the same bug as what you are fixing in package:build even though it has the exception.

**Comment by sigurdm** [comment]
We should check if this is still an issue

**Comment by sigurdm** [comment]
@isoos

**Comment by isoos** [comment]
Checked a local analysis with a `pubspec.yaml` without `version` field, it was working, I think this has been fixed.
