### ISSUE TITLE
Dart files are not detected on Windows

### ISSUE THREAD

**Issue by axel-op** [dart-lang/pana#614]
Currently, Dart files are detected like this:

```dart
var dartFiles =
        await listFiles(pkgDir, endsWith: '.dart', deleteBadExtracted: true)
            .where((file) => file.startsWith('bin/') || file.startsWith('lib/'))
            .toList();
```

On Windows, this results in an empty list.
Because of this empty list, the dartanalyzer part isn't executed at all.

**Comment by isoos** [comment]
Good catch, thank you for taking the time and fixing it!
