### ISSUE TITLE
A new major version of a dependency should not immediately give penalty

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#633]
If package `A` depends on `B` with the version constraint of `^3.5.0`, and `B 4.0.0` is released, `A` is immediately given score penalty for not matching the new version. We should only apply penalty after a grace period (e.g. 30 days?)

**Comment by sigurdm** [comment]
Don't we wan't to do it as fast as possible to motivate package authors to fix it as \fast as possible?

**Comment by sigurdm** [comment]
Closing as wontfix
