### ISSUE TITLE
Check compileSdkVersion of packages on pub.dev

### ISSUE THREAD

**Issue by deadsoul44** [dart-lang/pana#636]
Hello,

I think pub.dev should also check compileSdkVersion of packages to calculate maintenance points. For example, I had issues with the following package and manually updating its compileSdkVersion from 27 to 29 solved the issue. The package does not deserve 100 maintenance and 100 health points.

https://pub.dev/packages/flutter_twitter

Decrease in points can be calculated according to compileSdkVersion requirement.

https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

**Comment by sigurdm** [comment]
We are now doing much better here.

Closing as obsolete.

Please open a new issue if there is still more we should do.
