### ISSUE TITLE
Create a new tag for all flutter plugins

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#640]
I think we could give packages that are plugins a special tag `is:flutter-plugin`.

That way we can search for them should we ever want to.

**Comment by sigurdm** [comment]
Should this only cover new-style plugins? Ie. we detect it by detecting 
```
flutter:
    plugin:
```
in the pubspec.yaml?

**Comment by jonasfj** [comment]
This shipped a while ago.
