### ISSUE TITLE
Bug in "Package is a good, trustworthy dependency"

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#670]
On staging, `/packages/retry/score`:

"Could not run pub outdated: Exception: pub outdated exited 65. StdErr: The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again."

**Comment by sigurdm** [comment]
Fixed in https://github.com/dart-lang/pana/commit/6097bc3f7c555684a28540d9cb33d65a581318db#diff-e02cb551372cdea99b4ad1ec964d7497R311
