### ISSUE TITLE
Add scoring section for null-safety compatibility

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#677]
@mit-mit, how many points do you think we should give for null-safety migration? 20 points?

**Blocked until** a migration guide is out and a pre-release of Dart advocates publishing null-safety migrated packages.

**Comment by mit-mit** [comment]
I think I'd like to repurpose the Dart 2 section and it's 20 points for nulls safety.

**Comment by sigurdm** [comment]
We already took out the dart 2 section for the documentation

**Comment by mit-mit** [comment]
Ah, got it. Well, then we just add a new 20 points section. We can go higher with the new system!

**Comment by mit-mit** [comment]
A concrete check that I'd like to see here is for packages that declare support for null safety (via SDK constraint), but don’t support sound null safety during analysis

**Comment by sigurdm** [comment]
Do I understand the scoring here? One would get full points for either:

* Being a pre-null-safety package
* Being a package that opts in, and with all dependencies resolvable to null-safety-opted in packages (with no opt-outs in files).

But no points for opting in, but having not-opted-in files

**Comment by leafpetersen** [comment]
Is this still planned?

**Comment by mit-mit** [comment]
Yes, I believe so!

@sigurdm, can you elaborate on what you mean by being a "pre-null-safety" package? My idea was that you'd only get these 20 points if you support null safety.

**Comment by sigurdm** [comment]
> @sigurdm, can you elaborate on what you mean by being a "pre-null-safety" package? 

I interpreted your statement: "A concrete check that I'd like to see here is for packages that declare support for null safety (via SDK constraint), but don’t support sound null safety during analysis" that we would give points to both packages that do not claim null-safety support in their language version, **and** packages  that claim support without having non-null-safety dependencies.

> My idea was that you'd only get these 20 points if you support null safety.

I guess that mean only the second category would get the points.

**Comment by mit-mit** [comment]
> I guess that mean only the second category would get the points.

Yes, that is my suggestion.
