### ISSUE TITLE
Detect which version constraints cause issues

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#70]

**Comment by kevmoo** [comment]
*This* is super tricky.

You mean debug the version solver, right?

**Comment by isoos** [comment]
There are two options here:

- Parse the version solver output. AFAIR we have tuned down the logging level because it was too large, and it may not be on the output. However if it is still in the output, this would be the best to do.

- We could remove/uncomment the dependencies one-at-a-time, and if pub gets to resolve it, then we mark it as a potential root cause. If multiple ones get into the list, then we can treat them as the conflicting ones. Hacky, but would reflect a very simple debugging workflow in the absence of tooling support.

**Comment by isoos** [comment]
This is something we could use: https://pub.dartlang.org/packages/pub_mediator

**Comment by kevmoo** [comment]
Indeed!

**Comment by thosakwe** [comment]
This could actually be feasible soon, once https://github.com/thosakwe/pub_mediator/issues/1 is resolved.

I've submitted a PR to the `pubspec` package to support `sdk` and self-hosted dependencies. Just waiting for that to be merged before I can really do anything.

**Comment by kevmoo** [comment]
@nex3 is also working hard on improvements to the `pub` clint, which should make understanding "version lock" much easier.

**Comment by isoos** [comment]
This is outside of the scope for pana. I think once the `pub` client reports it, it will surface in our report too.
