### ISSUE TITLE
Support CR as line terminator

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#715]
Some source files uses CR as line terminators, we fixed https://github.com/dart-lang/pana/issues/713 by ignore the `RangeError`.

The issue can be reproduced with `dart bin/pana.dart --flutter-sdk /workspace/flutter --report -s hosted flutter_waya 1.0.5`, because `flutter_waya` version `1.0.5` has a file `lib/src/widget/custom/delegate/ChineseCupertinoLocalizations.dart` which uses CR as line separators.

**Comment by sigurdm** [comment]
Maybe we should rather detect this and subtract some points.

I think it is reasonable to require packages to use either the windows or unix convention.

**Comment by sigurdm** [comment]
I think we will close this, as CR is a very uncommon line-terminator and we have a workaround in place to not crash.
