### ISSUE TITLE
mailto: links are marked as insecure

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pana#729]
From a community member:

> There's a bug with the URL rule that marks email links as insecure:
![image](https://user-images.githubusercontent.com/2319867/87572701-cadfce80-c680-11ea-8174-e6f3e6e323a1.png)

**Comment by searchy2** [comment]
Thanks for filing this issue! I'm the one who raised it. Checked in other packages and can confirm it marks email links as insecure.
