### ISSUE TITLE
[BUG]  SDK contraint for up-to-date dependencies not handled correctly

### ISSUE THREAD

**Issue by Pante** [dart-lang/pana#749]
I think it's unfair to penalize people for using versions of Dart above 2.8.1.

![big_off](https://user-images.githubusercontent.com/9427324/88547072-cedff900-d04f-11ea-81a4-fae1c650b1df.PNG)

**Comment by isoos** [comment]
@Pante: thanks for reporting this, it seems to be a bug. We do use `2.8.4` as the latest stable SDK and this shouldn't be reported as an issue.
