### ISSUE TITLE
Validation fails for mailto Urls

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pana#761]
From [Ray Li on twitter](https://twitter.com/RayLiVerified/status/1283429250364772352):

![image](https://user-images.githubusercontent.com/13644170/89422500-b8aff800-d735-11ea-83a0-e89127cf8726.png)

**Comment by isoos** [comment]
Duplicate of #729
Fixed in https://github.com/dart-lang/pana/pull/730
