### ISSUE TITLE
`scores` command no longer supported?

### ISSUE THREAD

**Issue by pq** [dart-lang/pana#768]
As of today, I'm seeing this  failure:

```
Running pana...
Could not find an option named "scores".
```

https://travis-ci.org/github/dart-lang/linter/jobs/716931805

Here's where we're using it:

https://github.com/dart-lang/linter/blob/master/tool/pana_baseline.dart

Has that option been  removed?

**Comment by isoos** [comment]
Yes, 0.14 has many breaking changes, including the `scores` flag and also what we report as score.

**Comment by pq** [comment]
Ah, thanks!  It looks like the JSON format changed too.  I'm guessing what was the `"maintenance"` score is now closest to `"grantedPoints"`?

**Comment by isoos** [comment]
`grantedPoints` is "pub points" on pub.dev. The old `health`, `maintenance` and generic package-level issues/suggestions are gone, we have only a few larger report sections and a much simpler point-allocation.

**Comment by pq** [comment]
Interesting, we're getting penalized 20 point for failing to support multiple platforms.  Could you advise what we should do to remedy?  (Or just live with it?)

Thanks for the help!

**Comment by isoos** [comment]
For now we just live with it (there are many packages in the same situation, they are scored the same way, so relative "status" is the same). We are planning to improve upon that based on the feedback we've got so far...

**Comment by pq** [comment]
Good deal.  Thanks!
