### ISSUE TITLE
Proposal: Factor deprecated api use into package scoring

### ISSUE THREAD

**Issue by Piinks** [dart-lang/pana#796]
We're getting ready to start removing deprecated API from Flutter on a regular schedule. 

This work has not begun yet, but in discussing ways to successfully implement an end-of-life policy for deprecations, the idea was raised to incorporate deprecated api use into the scoring system on pub. This could be possible by checking the analysis settings of a package, deprecated member use can be configured to cause build failure.

Ideally, this would help motivate package authors to migrate their code and keep packages well maintained and up to date.

Tracking for Flutter deprecation policy work: https://github.com/flutter/flutter/issues/59180

**Comment by sigurdm** [comment]
We already factor in warnings from dart analyze.
I believe deprecated api usage is already a warning - so I think we already have this.

This can be circumvented by adding `// ignore:`-lines but I think that is fair. It shows that the author at least considered that the api is now deprecated.

**Comment by sigurdm** [comment]
Sounds like we are doing well here. Closing
