### ISSUE TITLE
Testing not working properly after pana validation

### ISSUE THREAD

**Issue by Arunsanthoshh** [dart-lang/pana#798]
In simple flutter app, I have getting more issues when using the **flutter test** command, once pana validation done.

**Issue replication steps--**
1. Create a simple flutter app. 
2. Use **flutter test** command in terminal. (It has worked fine)
3. Use **pana** command in the terminal. (It will validate the corresponding project)
4. Then again using the **flutter test** command. (In this case, we have getting more number of issues)

**Comment by isoos** [comment]
Since the original report we've updated `pana` to copy the package into a temporary directory, and apply local modifications only on the copy, and not on the original. This should resolve this issue.
