### ISSUE TITLE
Refine null-safety analysis to only consider imported libraries from dependencies

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#804]

**Comment by sigurdm** [comment]
Do we start in all libraries from the root - or just from the "primary libraries" ?

**Comment by jonasfj** [comment]
I think we would start from any library in `lib/` (maybe excluding `lib/src/` if not imported/exported from `lib/`).

**Comment by mit-mit** [comment]
One example that is hitting this: Flutter plugins (e.g. https://pub.dev/packages/url_launcher/versions/6.0.0-nullsafety.1), which are currently not tagged as supporting null safety:

```
> url_launcher that depends on:
> url_launcher_windows that depends on:
> flutter that depends on:
> sky_engine where ui/ui.dart is opting out from null-safety.
```

**Comment by isoos** [comment]
Another example reported here: https://github.com/dart-lang/pub-dev/issues/4277
