### ISSUE TITLE
Refine null-safety analysis with basic understanding of allowed_experiments.json

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#805]
Entries in `allowed_experiments.json` can opt-into null-safety with language-version 2.10, and few things still do this.

**Comment by jonasfj** [comment]
As this is a temporary we can probably just hardcode the package names currently listed in `allowed_experiments.json`, and then go back and remove in a few weeks.

**Comment by sigurdm** [comment]
Done in: https://github.com/dart-lang/pana/pull/806
