### ISSUE TITLE
Pub.dev filters for web platform exclude dev dependencies that work on projects targeting the web.

### ISSUE THREAD

**Issue by fatherOfLegends** [dart-lang/pana#808]
My team maintains a package for testing. (golden_toolkit) I noticed our package and all other packages that depend on flutter_test are docked points and filtered out of search when marking web as your platform because they are not compatible with the web target but these package work just fine for an app targeting the web when used as a dev dependency like they are intended. I am less concerned about the overall score and more concerned about developers overlooking the package due to misinformation.

**Comment by sigurdm** [comment]
You can now override the platform detections by specifying "platforms" in your pubspec.yaml
