### ISSUE TITLE
Support sound null-safety broken for Flutter packages

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/pana#811]
For some reason PANA sometimes reports that Flutter packages do **not** support sound null-safety because of the `flutter` dependency:

* `package` that depends on:
* `flutter` that depends on:
* `sky_engine` where `ui/ui.dart` is opting out from null-safety.

---

I do not understand what to do about it and I also cannot share an example because it magically disappeared for me after a while or after publishing a new version.

**Comment by sigurdm** [comment]
That is because until recently ui/ui.dart (in the flutter engine) would have a language version marker:
```
// @dart=2.10
```
And pana would consider that opting out of null safety.

This was too simple though. Because the dart sdk contains a list of package names that are treated special. Essentially these packages opt in to null-safety already from language version 2.10.

Since then these markers have been removed from flutter. Pana has learnt about those special packages (and pana no longer even considers the contents of dart:ui packages). So life should slowly start getting better :).

**Comment by creativecreatorormaybenot** [comment]
@sigurdm Just out of curiosity: the PR you mentioned is already almost a week old.  
Was it deployed to Pub just recently?

Because I still saw the issue I reported on Sunday :)

**Comment by sigurdm** [comment]
Which package had this behaviour Sunday - does it still?

It takes some time for new analyses to come alive after a deploy. Until then the old version might still show.

**Comment by creativecreatorormaybenot** [comment]
@sigurdm Well, it showed it for a while and then stopped showing it.

See [`wakelock`](https://pub.dev/packages/wakelock/versions/0.3.0-nullsafety.0/score) - it showed it for a while when I deployed `0.3.0-nullsafety.0`.  
I only deployed one null safety version, though. The previous version was from Nov 8 🤔

**Comment by sigurdm** [comment]
So I guess things are good now?

**Comment by creativecreatorormaybenot** [comment]
@sigurdm Yes, that is why I agreed with you closing the issue :)



The question was

> Just out of curiosity:

Because I was interested in how PANA is deployed to Pub I guess.

**Comment by sigurdm** [comment]
Pana is upgraded in pub.dev by changes like this: https://github.com/dart-lang/pub-dev/pull/4292/files . That also updates the "runtime version" of pub.dev

A new pub.dev release is deployed, and will do analysis, and store the results as they are done marked with the runtime analysis. This can happen even before traffic is switched.

The "live" version of pub.dev (the one currently serving traffic) will show the newest available analysis data (but not newer than itself)

That means we can switch traffic before all analysis is done.
