### ISSUE TITLE
How to integrate into CI

### ISSUE THREAD

**Issue by kentcb** [dart-lang/pana#843]
I was thinking of using pana in the CI pipeline for a Dart package because that way I can trap anything that would prevent me publishing. However, I'm finding it far less obvious how to do so than I expected.

The problem is that simply running `pana --no-warning` does not differ its exit code based on whether there are issues or not. Therefore, I need to perform extra steps to detect a failure (so that I can trigger a failure in the CI step). I'm not even sure the best way to do this yet, but am tossing up between either parsing the final line of output (`Points: 100/100.`) or checking whether there are any modifications to files under git's purvey (but might have to ignore `pubspec.lock`, for example).

Am I way off base here? Is there an easy way to integrate into a CI pipeline?

**Comment by sigurdm** [comment]
Yeah - pana is not really (currently) designed for running in CI. It is mainly thought of as an aggregator of stats from other tools.

I can see how this could currently be attractive, as some of the checks don't have a counterpart in other tools.

One issue with exiting 0 iff the score is 100/100 is that some packages will not ever get max points (think https://pub.dev/packages/win32 - it will never support all platforms).

Between your options I would currently go with the parsing of the output (a simple grep could perhaps work ok).

**Comment by isoos** [comment]
> One issue with exiting 0 iff the score is 100/100 is that some packages will not ever get max points (think https://pub.dev/packages/win32 - it will never support all platforms).

We could have an option for threshold: `--exit-code-threshold=20` will exit 0 if the score difference is 20 or less than the max available score.

**Comment by kentcb** [comment]
Yeah, other tools like `dartfmt` have similar flags. I was thinking it might make sense to specify the threshold as either an absolute number or a percentage.

For anyone following in my footsteps, here are the bash commands in my CI step. This is for GitHub Actions, but should work in any bash CI environment. I may turn it into a Marketplace Action if I feel it's worth it, but probably not.

I am far from a bash expert, so any improvement recommendations are welcome.

```bash
- name: Analyze package with Pana
  run: |
    pub global activate pana

    REQUIRED_RATIO=1.0
    TEMP_FILE=/tmp/pana_results.txt

    # Run pana, piping the output to both stderr and into a grep to find the result in the last line.
    pana --no-warning | tee /dev/stderr | tail -1 | grep -o -E '[0-9]+' > $TEMP_FILE

    # Extract score and calculate ratio.
    SCORE=$(cat $TEMP_FILE | head -1)
    TOTAL=$(cat $TEMP_FILE | tail -1)
    RATIO=$(echo "scale=2; $SCORE / $TOTAL" | bc -l)
    MEETS_REQUIRED_RATIO=$(echo "$RATIO >= $REQUIRED_RATIO" | bc -l)

    if [[ "$MEETS_REQUIRED_RATIO" != "1" ]]; then
      echo "Score of $SCORE out of $TOTAL is a ratio of $RATIO, which is not sufficient to meet the required ratio of $REQUIRED_RATIO"
      exit 1
    fi
```

You can set `REQUIRED_RATIO` to suit your needs, such as `0.75` to require a score of at least 75% the total available.

---

Another slight annoyance I've found with running `pana` in CI is that running `dart test` afterwards fails:

```
Run dart test
  dart test
  shell: /bin/bash -e {0}
  env:
    PUB_CACHE: /home/runner/.pub-cache
Failed to precompile test:test:
../../../.pub-cache/hosted/pub.dartlang.org/test-1.16.5/bin/test.dart:7:1: Error: Error when reading '/tmp/pana.1614655302937.FIRDFJ/hosted/pub.dartlang.org/test-1.16.5/lib/src/executable.dart': No such file or directory
export 'package:test/src/executable.dart';
^
Failed to precompile test:test:
../../../.pub-cache/hosted/pub.dartlang.org/test-1.16.5/bin/test.dart:7:1: Error: Error when reading '/tmp/pana.1614655302937.FIRDFJ/hosted/pub.dartlang.org/test-1.16.5/lib/src/executable.dart': No such file or directory
export 'package:test/src/executable.dart';
^
You need to add a dev_dependency on package:test.
Try running `dart pub add --dev test`.
```

This is true even if I deactivate `pana` before running `dart test`. For now, I've switched the order to run tests first, which is likely better anyway, but mindful that this may bite me later. I was surprised that Pana doesn't itself run tests and reduce the score for any failures.

**Comment by isoos** [comment]
> Another slight annoyance I've found with running pana in CI is that running dart test afterwards fails:

I think this is because `pana` will modify (and then restore) `pubspec.yaml` while also running `pub upgrade` on it. It is a side-effect (in the package resolution) we want to eventually fix, but so far it was not blocking most uses. Have you tried running `pub get` between `pana` and `dart test`?

**Comment by kentcb** [comment]
> Have you tried running pub get between pana and dart test

No I hadn't. Good to know - I'll give it a shot and report back.

Meanwhile, I just found another annoyance: Pana seems to assume Flutter is installed and will deduct points if it can't find it on the PATH. There is a flag (`isRunningEnd2EndTest`) in the code that is `false` for Travis builds, but there's no way to control it through a flag. When using Pana in the context of building a Dart package, it would be useful to disable any Flutter-related checks.

**Comment by kentcb** [comment]
Can confirm that `pub get` after `pana` allows `dart test` to execute successfully.

**Comment by kentcb** [comment]
@sigurdm @isoos Any interest in me putting together some PRs to address these issues?

**Comment by sigurdm** [comment]
Perhaps we should be able to invoke pana with the sub-reports to create, and return non-zero if any of them does not give max points....
