### ISSUE TITLE
Redirected Homepage URL is showing as broken

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pana#879]
https://pub.dev/packages/win32/score complains that win32.pub is unreachable:
![image](https://user-images.githubusercontent.com/2319867/118702390-b650f300-b7c9-11eb-93b5-ebf3403252ca.png)

This is hosted on Google Domains and is just a redirect to https://pub.dev/documentation/win32/latest/

Surprised that this gave an error, since the backend infra is pretty durable. Is there a log to diagnose this? Or is it that pana gives an error for a redirected URL?

**Comment by isoos** [comment]
We are using package:safe_url_check with the defaults, which is following 8 redirects:
https://github.com/google/dart-neats/blob/master/safe_url_check/lib/safe_url_check.dart#L107

I think the issue here may be ipv4/ipv6 or other network setting: from the browser, I can reach win32.dev, and it redirects properly, however curl gets me:
```
curl https://win32.dev/
curl: (6) Could not resolve
```

**Comment by jonasfj** [comment]
Maybe we should try with `win32.pub` :see_no_evil: (credits athomas for noticing)

**Comment by jonasfj** [comment]
```
[safe_url_check]$dart test -r expanded
00:00 +0: test/unique_local_ip_test.dart: isUniqueLocalIpV6
00:00 +1: test/private_ip_test.dart: isPrivateIpV4
00:00 +2: loading test/safe_url_check_test.dart
00:00 +2: test/safe_url_check_test.dart: safeUrlCheck("https://win32.pub")
00:00 +3: test/safe_url_check_test.dart: safeUrlCheck("https://google.com")
00:00 +4: test/safe_url_check_test.dart: safeUrlCheck("https://github.com")
00:01 +5: test/safe_url_check_test.dart: safeUrlCheck("https://github.com/google/dart-neats.git")
00:01 +6: test/safe_url_check_test.dart: !safeUrlCheck("https://github.com/google/dart-neats.git/bad-url")
00:02 +7: All tests passed!
```

Maybe we just need to analyze it again.

**Comment by timsneath** [comment]
Looks like this URL resolved upon a new analysis run: 
https://pub.dev/packages/win32/score

**Comment by sigurdm** [comment]
Looks like it is working.

Closing
