### ISSUE TITLE
Please exclude analyzer 1.6.0 in pubspec

### ISSUE THREAD

**Issue by simolus3** [dart-lang/pana#892]
My understanding is that `analyzer` version `1.6.0` is broken because it has an implicit contract on `package:meta` that it failed to express in its pubspec.

I think one of my package is is failing to pass pana because of this. [Moor](https://pub.dev/packages/moor/score) currently has an analysis score of 0/30 because

```
dartanalyzer exception: RangeError (index): Invalid value: Not in inclusive range 0..12: 13
```

Looking at [the source](https://github.com/dart-lang/sdk/blob/2242843b97b36e0ea0fddfdb47f24686f8931452/pkg/analyzer/lib/src/error/best_practices_verifier.dart#L1627-L1628) of the error when reproducing it locally:

```
SEVERE     Bad input?: Unhandled exception:
           RangeError (index): Invalid value: Not in inclusive range 0..12: 13
           #0      List.[] (dart:core-patch/array.dart:268:52)
           #1      BestPracticesVerifier._targetKindsFor (package:analyzer/src/error/best_practices_verifier.dart:1601:38)
           #2      BestPracticesVerifier.visitAnnotation (package:analyzer/src/error/best_practices_verifier.dart:253:17)
           #3      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:302:50)
           #4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
           #5      AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:145:17)
           #6      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1537:11)
           #7      RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:711:10)
           #8      BestPracticesVerifier.visitClassDeclaration (package:analyzer/src/error/best_practices_verifier.dart:323:13)
           #9      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
           #10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
           #11     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2112:21)
           #12     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:735:10)
           #13     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
           #14     LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:276:10)
           #15     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:158:9)
           #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
           #17     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:157:13)
           #18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:104:12)
           #19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1315:63)
           #20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
           #21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1286:20)
           #22     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1369:26)
           #23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:987:20)
           #24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2006:24)
```

`package:meta` recently added a new `TargetKind`, but not at the end of the `TargetKind` enum. I think that may break analysis when the analyzer is compiled with a different version of `meta` than the package it analyses. I don't know if this is really an `analyzer` bug, but my understanding is that this primarily affected an older analyzer version.

Could pana try to avoid analyzer version 1.6.0? I want my hard-earned analysis points :D

**Comment by simolus3** [comment]
Oh wait actually pana uses `dartanalyzer`, so it's not related to a dependency conflict :( Maybe this issue should be moved into the SDK?

There's a fairly obvious analyzer crash when the analyzer runs on code using a different version of the `meta` package than what the `analyzer` has been compiled with. It does `TargetKinds.values[indexOfSomeComputedConstant]`, so if the set of `TargetKinds` grows in a `meta` upgrade older analyzers may crash which is what's happening here. I think this may affect all packages compatible with `meta` version 1.4.0??

**Comment by isoos** [comment]
> Oh wait actually pana uses dartanalyzer

It uses both `dartanalyzer` (for SDK-specific analysis) and `package:analyzer` for the library-detection and platform classification, and the above stacktrace is coming from that. However, on pub.dev we are still stuck with `package:analyzer 0.41.2`, so it may not be the issue with 1.6.0, rather something else...

**Comment by simolus3** [comment]
Yeah I can reproduce this by just running `dartanalyzer lib` so it's probably unrelated to pana. I'll investigate further and open an issue on the SDK.
