### ISSUE TITLE
License detection: separate package?

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#91]
License detection is a neat, easy-to-separate feature which could live in its own package (e.g. `license`). Contribution to it would be easier, it would be normal there to have all of the different license texts part of the tests, but it won't put much drag on the `pana` repo. Thoughts?

**Comment by kevmoo** [comment]
Unless we have a 2nd user for it, I think we should avoid it. More to
manage.

**Comment by isoos** [comment]
No 2nd user yet.

**Comment by eseidelGoogle** [comment]
FWIW, Flutter has its own license package (for different reasons): https://github.com/flutter/engine/tree/master/tools/licenses I'm not suggesting we share code, just letting you know it exists in case it's useful to you.

**Comment by isoos** [comment]
@eseidelGoogle: It looks useful, thanks for sharing it! It would be nice to merge these into a standalone package...

**Comment by kevmoo** [comment]
@eseidelGoogle – I'd LOVE to understand how you found this issue. 😄 

`dart-lang` is happy to host such a package, although we've now hit 2 users – [not 3](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)).

I'm all for solving these types of problems in few places.

**Comment by eseidelGoogle** [comment]
@kevmoo I get auto-subscribed to all dart-lang repos as part of being an org member. :)   Inbox groups them by repository, and this one happened to be a new repo so I briefly looked at the issue emails.
