### ISSUE TITLE
Extend the scope of analyzer options with stagehand defaults?

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#94]
If these are good defaults for stagehand, maybe they are good for pana too?

https://github.com/dart-lang/stagehand/blob/master/templates/package-simple/analysis_options.yaml

**Comment by kevmoo** [comment]
Maybe?... 🤷‍♂️ 

All of these have issues – which is why they are lints and not baked into the platform. Not a high priority IMHO

**Comment by isoos** [comment]
I don't mind being opinionated when the linter rule can expose a high-risk error. It would be nice if we could have a statistics on all of the linter rules and the most popular packages... 📊
