### ISSUE TITLE
Examples aren't detected in package:rfw

### ISSUE THREAD

**Issue by Hixie** [dart-lang/pana#971]
https://pub.dev/packages/rfw/score claims that there's example, but there's four of them, and they follow the structure described in https://dart.dev/tools/pub/package-layout#examples.

**Comment by isoos** [comment]
As the linked package layout page describes, we have a fair number of file names that we detect as example file, and `package:rfw` doesn't have any of them. In such cases where the example folder has multiple sub-folders, we suggest to use the `example/README.md` to describe the content.

On the longer term, we could also scan the subfolders, collect the readme files, concatenate them (with downscaling the header sizes), and treat them as the top-level readme. However, the order of the folders will be arbitrary, and I think if somebody had the time to write multiple example projects, it may be better for them to control the order and the presentation of it through `example/README.md`.

**Comment by Hixie** [comment]
Ah, I see. It would be good to clarify the docs to say that you have to do the bottom part even if you have more than one example. Right now it reads as if you do the bottom part if you have one example, and if you have several, you use subdirectories.

**Comment by jonasfj** [comment]
https://pub.dev/packages/rfw/versions/1.0.0/score

![image](https://user-images.githubusercontent.com/149732/153384381-f1cbff5e-0750-4c00-8d81-98e57c115c2f.png)

**Comment by sigurdm** [comment]
Short term: Let us have pana give a different message if the example folder exists, but we cannot detect our usual patterns of examples.

Longer term: let us have source-listings of the entire example folder. Than we can just detect presence of an example folder.

**Comment by sigurdm** [comment]
Seems to be fixed by now
