### ISSUE TITLE
Lower pub scores for plugins that create too many threads

### ISSUE THREAD

**Issue by jacob314** [dart-lang/pana#988]
Flutter Plugins that create their own threads pools should be discouraged as this can lead  to applications that perform poorly on low end devices once a large # of plugins are used.

This could be a requirement for "Flutter Favorite" packages where we already perform some manual validation.

It is possible that static analysis could detect Android Java code calling  most of the threading APIs that should not be called from within a plugin that is reusing the thread pool that a Flutter app should use.
Fyi @dnfield for more context.

**Comment by jacob314** [comment]
SGTM

**Comment by sigurdm** [comment]
I don't think we have any idea of how this would be done in static analysis (most likely it is not even possible - halting problem etc).

I'll close for now, as I don't think we can do more from the pana side.
