### ISSUE TITLE
Support dual licensing in detection and expose it in the report.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#997]

**Comment by bharat-biradar** [comment]
@isoos The current license detector already supports multiple license detection. It's just that while displaying it on pub,dev we only take the license with the highest confidence and ignore the others. For example, if we see the output generated by the `license_detector_bin.dart` for some of the plugins on the pub.dev that have more than one license we can see both of them are being detected. I have attached a screenshot below. 
Plugins in screenshot"
- [mvc_pattern](https://pub.dev/packages/mvc_pattern)
- [allnotification](https://pub.dev/packages/allnotification/license)
- [pikaday_datepicker](https://pub.dev/packages/pikaday_datepicker)
![image](https://user-images.githubusercontent.com/62872048/146890708-23bf8114-b7c5-4c7a-baef-dbb736cbc409.png)

Another example with a file having 4 licenses
![image](https://user-images.githubusercontent.com/62872048/146889671-6b98ec1d-e64b-45f2-99c3-3b6406e5a5b3.png)

But [here](https://github.com/dart-lang/pana/blob/e0ce9194ba49458770eec78ed1709ad0ec8ecea8/lib/src/license.dart#L47-L54) while displaying it, we are just considering the first match. Maybe we can return a list here and also add a condition like the percentage of tokens claimed by all matches is greater than 0.8 or 0.9 to ensure it's not spam.

**Comment by JKRhb** [comment]
How about being able to use an SPDX identifier in the `pubspec.yaml` file (like `MIT OR Apache-2.0`) and then check if the license(s) are provided in the `LICENSE` file (or somewhere else)? This could also deal with the problem that the automatic detection sometimes can't determine the correct license when multiple ones (e. g. from third party software) are contained in the LICENSE file.

**Comment by sigurdm** [comment]
We would be happy to have volunteers help with this.

**Comment by isoos** [comment]
With the new `licenses` field in the `Summary` the first two package has been identified correctly (`mvc_pattern`, `allnotification`).

**Comment by sigurdm** [comment]
I think this is working correctly at this point.
